### ISSUE TITLE
On Browse Results Page, the TEI:title child element is not displaying

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#1]
![Screenshot 2020-03-02 10 36 13](https://user-images.githubusercontent.com/3083773/75696730-ab1bb100-5c71-11ea-9d18-71e57d0af7fc.png)

The first record should read: 
Ammianus Marcellinus. _History_, 14.11

Please wrap the title element in italics

p.s. all of these Caesarea work will be billed to a new PO

**Comment by davidamichelson** [comment]
In addition to wrapping /TEI/teiHeader/fileDesc/titleStmt/title/title in italics, please also wrap /TEI/text/body/desc[@type="abstract"]/title in italics.

**Comment by davidamichelson** [comment]
In addition the same title element is not wrapped in italics when it occurse in the How to Cite This Entry box (occurs three times in the box)

**Comment by wsalesky** [comment]
@davidamichelson Could we add a `@rend='italic'` to the title element? That makes more sense to me than programing that a title nested in a title should always be rendered as italic.

**Comment by davidamichelson** [comment]
We could, though I am not sure if that is good design in TEI. My inclination is that any thing in a title element should render as italic. Let's discuss.

**Comment by wsalesky** [comment]
@davidamichelson That is fine as long as titles should always be in italic. This is the TEI for the record in question: 
```
<title xml:lang="en" level="a">
   Ammianus Marcellinus.
   <title>History</title>
14.11
</title>
``` 

So if titles are always in italic it would render as: _Ammianus Marcellinus. History, 14.11_

Or I can programtically only italicize a nested tei:title/tei:title, which would get the desired display.

**Comment by davidamichelson** [comment]
Hmm, yes I see the problem. Let's wait and discuss in person.

**Comment by davidamichelson** [comment]
Render title in italics if title@level="m"

**Comment by davidamichelson** [comment]
@wlpotter will change anywhere in the document (titleStmt, abstract)

**Comment by wlpotter** [comment]
Note to self, the titles that need to be changed appear here:

/TEI/teiHeader/fileDesc/titleStmt/title/title
/TEI/teiHeader/profileDesc/creation/title
/TEI/text/body/desc/title

**Comment by wlpotter** [comment]
@wsalesky this change has been made in the data

**Comment by wlpotter** [comment]
I just realized that I was working on the branch with the anchors, rather than on master...I will make the changes on master now

**Comment by wlpotter** [comment]
Okay, now the data on master should be correct.

**Comment by wsalesky** [comment]
Looks good on browse, needs to be added to the work page title.
