### ISSUE TITLE
Testimonia Browse--Webhooks?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#102]
@wsalesky No rush, but it seems that the webhooks are not catching up perhaps? I made this change this morning
https://github.com/srophe/caesarea/blob/6ea979ef0b995776e68d2dd032998358ac9de230/testimonia/browse.html#L11

But it is not on the page.

Thanks!

**Comment by davidamichelson** [comment]
Same with https://github.com/srophe/caesarea/search?q=2020VUCDHlogo&unscoped_q=2020VUCDHlogo which does not seem to be able to call this file: https://github.com/srophe/caesarea/blob/master/resources/images/2020VUCDHlogo.png

**Comment by wsalesky** [comment]
Updated site and webhooks. Let me know if they are not working tomorrow.
