### ISSUE TITLE
Bibl Search by Place and Publisher return no results but should

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#105]
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/search.html?q=&title=&author=&subject-exact=&mss=&pub-place=Oxford&publisher=&start-date=&end-date=&idno=

http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/search.html?q=&title=&author=&subject-exact=&mss=&pub-place=&publisher=Brill&start-date=&end-date=&idno=

**Comment by wsalesky** [comment]
@fixed by adding the correct fields to the data configuration file.
