### ISSUE TITLE
Testimonia Linked Data Box has ghost bullets

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#108]
Removing the bibl links in the Testimonia record pages has left ghost bullets (as expected) in the linked data box. Could you please figure out how to remove them?

Thanks!

<img width="409" alt="Screen Shot 2020-08-12 at 4 07 26 PM" src="https://user-images.githubusercontent.com/3083773/90068349-1f915c00-dcb6-11ea-89bb-293dda403576.png">

**Comment by wsalesky** [comment]
Fixed
