### ISSUE TITLE
 /TEI/teiHeader/fileDesc/publicationStmt/authority #10 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#11]
See pull request https://github.com/srophe/caesarea/pull/10

**Comment by wsalesky** [comment]
Note: 
How to Cite This Entry full Bibliography citation we currently have the publisher hard coded as "Syriaca.org" and the Date hard coded.

Instead, could we generate this from the TEI record in the following places:

/TEI/teiHeader/fileDesc/publicationStmt/authority

and /TEI/teiHeader/fileDesc/publicationStmt/date (but just take the year) ?

Make to Srophe application, and all other dependent apps.

**Comment by wsalesky** [comment]
Fixed here and Srophe. Still need to update other apps.

**Comment by davidamichelson** [comment]
looks great, you can close issue if you are done.
