### ISSUE TITLE
In Bibl browse and search results the citation is displaying both the bibliography and the note version

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#111]
@wsalesky This needs fixing but if you want to wait until the AWS production version that is fine.

In the bibl module the citation is displaying twice per entry. The bibliography form (which we want) is followed by the footnote form (which should be suppressed).

Current:
Binyamina Ben-Dor, Immanuel, and Herman Hamburger. “Binyamina.” _IEJ_ 1 (1951 1950): 249. Immanuel Ben-Dor and Herman Hamburger, Binyamina, _IEJ_ 1 (1951 1950): 249.
URI: https://caesarea-maritima.org/bibl/EVU9Y3LQ

Revised:

Binyamina Ben-Dor, Immanuel, and Herman Hamburger. “Binyamina.” _IEJ_ 1 (1951 1950): 249. 
URI: https://caesarea-maritima.org/bibl/EVU9Y3LQ

<img width="1235" alt="Screen Shot 2020-08-13 at 11 34 10 AM" src="https://user-images.githubusercontent.com/3083773/90161839-5a000500-dd59-11ea-8858-0cb380819f44.png">

**Comment by wsalesky** [comment]
Fixed
