### ISSUE TITLE
"TextLang:" Label in Bibl module

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#112]
On the record page, there is a label "TextLang"

I cannot find this label anywhere in the app, so I suspect that it is auto-generated from the TEI element name?

I want to change it to "Language of Publication:"

Is the solution to encode it here: https://github.com/srophe/caesarea/blob/42e67d408c8633791bc91e92ab7934f3edf743f4/resources/xsl/bibliography.xsl#L1331-L1337

Please advise and thanks for making such a clear and easy to understand app!

Also, can we ask the app to suppress this element when it is empty?

**Comment by davidamichelson** [comment]
<img width="604" alt="Screen Shot 2020-08-13 at 11 57 00 AM" src="https://user-images.githubusercontent.com/3083773/90163796-312d3f00-dd5c-11ea-97a1-ac63f578e549.png">

**Comment by wsalesky** [comment]
Any element without an explicitly mentioned template will use this: https://github.com/srophe/caesarea/blob/42e67d408c8633791bc91e92ab7934f3edf743f4/resources/xsl/bibliography.xsl#L1405

So all you need to do is add a template for `tei:textLang` like (important to use mode='full'): https://github.com/srophe/caesarea/blob/42e67d408c8633791bc91e92ab7934f3edf743f4/resources/xsl/bibliography.xsl#L1398

@davidamichelson do you want to add it, or would you like me to add it?

**Comment by davidamichelson** [comment]
Ooh, I will do it!

**Comment by wsalesky** [comment]
Fixed
