### ISSUE TITLE
Linked Data Box for Bibl Module

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#115]
For the Linked Data Box in Bibl Module

Format based on this example record:
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/JGRE45HR

If there is an author, put one bullet with the a label, if no author then leave blank.

Linked Data
This record has 2 connection(s).

Author:
- Search WorldCat Identities (this would be a link to 
http://worldcat.org/identities/find?fullName=M.%20Oren%20Paskal and it is fine if this link doesn't give the result we want).

Title:
- OCLC Worldcat (if there is a URI for OCLC world cat include this, if not, don't include)

NOTES:
If there are no connections (ie Author field is empty and there are no URIs other than Caesarea-Maritima.org and Zotero) then leave the box off completely as the app does currently.

If there are other URIS besides WorldCat for now include them like this:
Title:
- Other Linked Data (if there are any other URIs include them as links here)

**Comment by wsalesky** [comment]
@davidamichelson How does this look?

**Comment by wsalesky** [comment]
@davidamichelson I think this can be closed?
