### ISSUE TITLE
Temporary banner image for homepage

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#12]
@wsalesky could you please crop and use this image temporarily as a banner image on the homepage? Don't spend too much time on it as it will likely change.

Original:
https://commons.wikimedia.org/wiki/File:CAESAREA%27_KING_HEROD%27S_SEA_PALACE_AERIAL.jpg

Mock up crop:
![Mediawiki_CAESAREA'_KING_HEROD'S_SEA_PALACE_AERIAL](https://user-images.githubusercontent.com/3083773/75703792-cbea0380-5c7d-11ea-9611-3050fc870b4a.jpg)

Caption:
"An aerial view of the Herodian harbor and palace complex at Caesarea Maritima. Original photo created by Abraham Gracier, copyright 2012, and published by Wikimedia Commons (https://commons.wikimedia.org/wiki/File:CAESAREA%27_KING_HEROD%27S_SEA_PALACE_AERIAL.jpg). The image has been cropped and reused here under the terms of the Creative Commons Attribution-Share Alike 4.0 International license (https://creativecommons.org/licenses/by-sa/4.0)."

**Comment by wsalesky** [comment]
Added.
