### ISSUE TITLE
Replace "Banner.JPG"

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#128]
Please crop the file "aqueduct" (sent via e-mail) to replace the port picture which is currently here https://github.com/srophe/caesarea/blob/master/resources/images/banner.jpeg

**Comment by davidamichelson** [comment]
This may note be possible, but if you can keep any blue sky on the banner, the main title and editors' names could be put above in the blue sky above the architecture

**Comment by wsalesky** [comment]
@davidamichelson how does this look?

**Comment by davidamichelson** [comment]
Looks great! Thanks
