### ISSUE TITLE
Please change title fonts to serif

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#131]
This font is a good model: https://fonts.google.com/specimen/Domine but anything similar would be fine.

So on the landing page (https://caesarea-maritima.org/index.html) the following text would be in this serif font:

```
Caesarea-Maritima.org
A Digital Archive
Joseph L. Rife, Phillip I. Lieberman, and David A. Michelson, General Editors
```

```Caesarea Maritima: A Thesaurus of Testimonia```

```Caesarea Maritima: A Comprehensive Bibliography```

**Comment by davidamichelson** [comment]
Please also change the font by the logo: Caesarea-Maritima.org

**Comment by davidamichelson** [comment]
Please make this change apply across the site, so also on the module landing pages.

**Comment by wsalesky** [comment]
Done.  @davidamichelson if you can just do a quick review and comment here if I missed anything. If it looks good you may close the issue.

**Comment by davidamichelson** [comment]
Looks Great! Thanks!
