### ISSUE TITLE
Removed from Bibliography Advanced Search: by DOI and by Online Items

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#136]

**Comment by wsalesky** [comment]
@davidamichelson These are holdovers from Biblia Arabica I do not know if the Caesarea data has the same hooks to make these work. The DOI is searching idno and the viewable online is searching indo's for anything that does not match 

- https://biblia-arabica.com
- https://www.zotero.org
- https://api.zotero.org

**Comment by davidamichelson** [comment]
WE need to let Winona know what parameters to use.

**Comment by davidamichelson** [comment]
@wsalesky Please comment out theses features from Advanced Search:

ISBN / DOI / URI:
Only items viewable online:

**Comment by wsalesky** [comment]
Done
