### ISSUE TITLE
New Tabs for Bibliography Browse Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#137]
These are for here: https://caesarea-maritima.org/bibl/browse.html

Please make new tabs for Browse By similar to Testimonia Page:

Order of Tabs:

"By Author", "By Title", "By Date"

Default should be that https://caesarea-maritima.org/bibl/browse.html takes one to "By Author"

Date Range Slider should stretch all the way across the page above both the facets and the results list.

"By Author" Tab 
Details:
Should use the alphabet at the top to allow filter by first letter of Author's last name.
Should have Date Range Slider all the way across the top
Side Facets should be Date Ranges in 25 year increments

"By Title" Tab 
Details:
Should use the alphabet at the top to allow filter by first letter of title (not by first letter of Author's last name as I think it now is supposed to).
Should have Date Range Slider all the way across the top
Side Facets should be Authors (as at present) and then a second set which is Date Ranges in 25 year increments

"By Date" Tab 
Details:
No Alphabet Range
Should have Date Range Slider all the way across the top
Side Facets should be Authors and then a second set which is Date Ranges in 25 year increments

**Comment by wsalesky** [comment]
In process

**Comment by wsalesky** [comment]
@davidamichelson Please take a look and let me know what you think.

**Comment by davidamichelson** [comment]
This is working great! There is a data issue which I need to fix. https://github.com/srophe/caesarea-data/issues/44
