### ISSUE TITLE
In bibliography module sort menu change Author to Author/Editor

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#139]
Could we change "Author" here to "Author/Editor" please:

<img width="340" alt="Screen Shot 2021-01-04 at 12 52 15 PM" src="https://user-images.githubusercontent.com/3083773/103568771-c6f07480-4e8b-11eb-8326-e3bac012b72d.png">

**Comment by davidamichelson** [comment]
I couldn't find where to change this myself, if you let me know the line of code I would love to do it myself so I understand. Thanks!

**Comment by wsalesky** [comment]
@davidamichelson You can try changing it here:
https://github.com/srophe/caesarea/blob/master/bibl/browse.html#L26

This may work, or it may be hardcoded (ugh!) in the XQuery, try this first though.

**Comment by davidamichelson** [comment]
You are right, that will call something in the Xquery to rename that. I found where it renames pubDate as Date: https://github.com/srophe/caesarea/blob/2183f97eca2f46e22540d361444f19d790d418a5/modules/lib/paging.xqm#L141

But I can't find where it renames "author" do I dare change it here?

**Comment by wsalesky** [comment]
Fixed.
