### ISSUE TITLE
https://github.com/srophe/caesarea/blob/master/expath-pkg.xml

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#14]
Do we need to edit the mention of Syriaca.org out of here:

https://github.com/srophe/caesarea/blob/master/expath-pkg.xml

**Comment by wsalesky** [comment]
You mean the namespace? We can, but we don't need to. Although now that I think of it, the app should probably all be in the Srophe.org namespace instead of the Syriaca.org namespace.

**Comment by davidamichelson** [comment]
I mean this line:

```name="http://syriaca.org/caesarea"```

Should it be Caesarea-Maritima.org or Srophe.app?

**Comment by wsalesky** [comment]
Closing this as it is fixed in the exist5.0 branch on all the apps.
