### ISSUE TITLE
I broke the spacing of the module boxes on https://caesarea-maritima.org/index.html

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#157]
I was trying to remove "About Caesarea-Maritima.org" Header Line in this issue: https://github.com/srophe/caesarea/issues/141 and commit https://github.com/srophe/caesarea/commit/02b41e43465a990d2edbbc6e57731aa9f72d66d4

But now the balancing of the modules is off, see image.

See the mistake I made: https://github.com/srophe/caesarea/commit/02b41e43465a990d2edbbc6e57731aa9f72d66d4#r45635396
<img width="2540" alt="Screen Shot 2021-01-04 at 12 20 11 PM" src="https://user-images.githubusercontent.com/3083773/103566507-bb02b380-4e87-11eb-8f9d-d25bb6fbfd4c.png">

Please fix :)

**Comment by wsalesky** [comment]
@davidamichelson Does this look any better? Unfortunatly this sort of display is not something the internet excels at, so you did not do anything wrong.

**Comment by davidamichelson** [comment]
@wsalesky Thanks, though now the old issue https://github.com/srophe/caesarea/issues/127 of the buttons is back (but only at certain zoom levels) see attached:

<img width="2525" alt="Screen Shot 2021-01-04 at 3 03 35 PM" src="https://user-images.githubusercontent.com/3083773/103579567-1dff4500-4e9e-11eb-8ffd-a87aaaf68558.png">

Would a solution be to put the buttons above the text (so before Caesarea Maritima: A Collection of Testimonia) so that the buttons would always be on the first line?

**Comment by wsalesky** [comment]
@davidamichelson What do you think of the new button placement? I'm not 100% happy with the look, but will come back to it at the end of the day, if I come up with something better.

**Comment by davidamichelson** [comment]
@wsalesky I think @wlpotter and I found something better than the buttons, how does it look? I also make the pictures clickable to go to the browse.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter much better than the buttons. Thank you!

**Comment by davidamichelson** [comment]
Great, I would like to make the pictures clickable on Syriaca.org too
