### ISSUE TITLE
I can't get a space to display on line 52 of https://caesarea-maritima.org/index.html

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#159]
See https://github.com/srophe/caesarea/blob/7fb591220b3ba7e06f4f3cf3a72a54f9a6eac78b/index.html#L52
In the HTML there is a space: ```enjoyment. <a href="./about.html">Learn more```
But in the browser there is none: ```enjoyment.Learn more...```

**Comment by davidamichelson** [comment]
Any ideas on what I am doing wrong? Thanks!

**Comment by wsalesky** [comment]
@davidamichelson did you push this directly to the master branch?

**Comment by davidamichelson** [comment]
Yes, this link shows you the code on the master branch with the space present, but on the server/in my browser it is not appearing: https://github.com/srophe/caesarea/blob/7fb591220b3ba7e06f4f3cf3a72a54f9a6eac78b/index.html#L52 

When I do view source in the browser, that white space is trimmed ```enjoyment.<a href="./about.html">Learn more```

**Comment by wsalesky** [comment]
Seems to have been fixed with my fix to the buttons. Not sure what was going on there.
