### ISSUE TITLE
Can you please set the Leaflet Maps default base map to the DARE "imperium" map?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#160]
If you can let me know how we do that, please do! What is the default on Syriaca.org/geo?

<img width="1200" alt="Screen Shot 2021-01-04 at 3 39 22 PM" src="https://user-images.githubusercontent.com/3083773/103582260-1f7f3c00-4ea3-11eb-9c42-5d43bb67363d.png">

**Comment by davidamichelson** [comment]
Okay so it looks like maybe leaflet or somebody did an update that wiped our default? For now, please just set imperium to default.

As a larger problem to look into:
http://syriaca.org/geo/browse.html?view=map and https://bqgazetteer.bethmardutho.org/ are now both defaulting to "terrain" but really that "terrain" map is too modern for any of these three projects. I thought that we had another map besides "imperium" before. I can't remember it's name, was it from AWMC or ISAW? I will have to look it up (was it this http://awmc.unc.edu/wordpress/tiles/) unless you remember. Thanks!

**Comment by davidamichelson** [comment]
Okay interesting, I looked at https://pleiades.stoa.org/@@search?SearchableText=+Thynias

At it seems that their ancient base map is on the fritz and I think that is what we use. So don't touch http://syriaca.org/geo/browse.html?view=map and https://bqgazetteer.bethmardutho.org/  for now, but please set c-m.org to use imperium for now if you can.

**Comment by davidamichelson** [comment]
Are these issues related: https://github.com/srophe/caesarea/commit/9a86ec7b56e081d8d8548461794dae40ad6798d3

**Comment by wsalesky** [comment]
@davidamichelson Yes these are related to 9a86ec7, the tiles we were using no longer exist, at least not in the location we were calling them from. I do (or rather I now) have a mapbox token that I am using for the new layers. The tiles went missing over the holiday and my patch was to use the the free mapbox options, which still require a token. We will need to do some investigating to find maps that better match the data, but I did not want us to have no map tiles at all. Which is what is happening here  https://pleiades.stoa.org/@@search?SearchableText=+Thynias  and https://peripleo.pelagios.org/ui . Originally we were using the same tiles that Pleiades was using. Maybe we can ask Tom Elliot about this?

**Comment by davidamichelson** [comment]
Okay, good to know. I will reach out to Tom. For now please use the ones
you have and set imperium as the default if you are able.

Thanks!

**Comment by wsalesky** [comment]
@davidamichelson I can set the imperium as the default, however, there are issues with that map as well, not all the tiles render, I don't know if this is by design or not?  What do you think?

**Comment by davidamichelson** [comment]
That is fine that DARE Imperium is missing some tiles, our data falls inside the tiles it does have. So please set as default for now.

**Comment by wsalesky** [comment]
Done. Should we change the zoom? So it only shows the part of the map with tiles?

**Comment by davidamichelson** [comment]
Yes that would be good  please aim to basically just approx the area where there are pins

**Comment by wsalesky** [comment]
@davidamichelson Done. We can tweak it if you want any changes. I set zoom to 4 and centered on Caesarea.

**Comment by davidamichelson** [comment]
@wsalesky Thanks this looks good, thanks!
