### ISSUE TITLE
Update HTML Display to Allow Sort by Proper Name

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#161]
@wsalesky 

We would like to make the following change to the data and the app. If you have time in the AM please try it out for this record:

https://caesarea-maritima.org/testimonia/44

(I changed the data model in record 44 only).

If not, no worries!

```
<persName ref="http://viaf.org/viaf/100226923" role="author"><name>Cornelius</name> <name sort="1">Tacitus</name></persName>
```

Please have your facet browse and author search use this path /TEI/teiHeader/profileDesc/creation/persName (assuming that is what you currently use, if not let us know) and then use the TEI:name sort="1" name for alphabetization. 

So in this model Cornelius Tacitus would show up under T not C. But the full contents of the persName would display as "Cornelius Tacitus" in the Browse facet author menu.

For Documentation:
Following the practice of the [EpiDoc Guidelines](https://epidoc.stoa.org/gl/latest/idx-persnames.html), our schema will uses only TEI:name as a child of TEI:persName since the child elements in the TEI (e.g. TEI:forname) are not well suited for Greek or Latin nomenclatures. To facilitate alphabetical sorting and faceting by name, the [@sort](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.personal.html) attribute is used with a value of "1" to indicate the name for sorting purposes.

**Comment by wsalesky** [comment]
@davidamichelson How do  you want this to show up in the facet? Currently I have it like this: 
<img width="1356" alt="Screen Shot 2021-01-08 at 1 24 58 PM" src="https://user-images.githubusercontent.com/1168206/104050789-22d13b00-51b5-11eb-8efb-a24fcc3680f0.png">


Which is how I get it to sort correctly, because facets are stored in the db as strings. If you want to retain the document order I will need to rethink how facets work for authors.

**Comment by davidamichelson** [comment]
Okay, that's good for now. Let's chat next week about what we might need to do. Thank you!

**Comment by davidamichelson** [comment]
I am assuming you have not pushed this yet to the server as I don't see it. So please do push that for now. Thanks!

**Comment by wsalesky** [comment]
@davidamichelson This has been moved to production server.

**Comment by davidamichelson** [comment]
Thanks and great work!
