### ISSUE TITLE
Browse by Letter, Facet, and Sort combine for confusion ;)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#162]
This issue occurs in browse testimonia by author>letter  for example in by author>J:
 https://caesarea-maritima.org/testimonia/browse.html?lang=&alpha-filter=J

It seems to work fine but note that Jerome is in the results but not listed in the facets:

<img width="1176" alt="Screen Shot 2021-01-04 at 4 10 57 PM" src="https://user-images.githubusercontent.com/3083773/103584708-738c1f80-4ea7-11eb-8e95-ded1282f7d49.png">

Next if on this same page one selects Sort>Title, then all the results change and the only visible results are by Flavius Josephus and neither Justinian nor Jerome are on the page or in the factes.

<img width="1252" alt="Screen Shot 2021-01-04 at 4 11 57 PM" src="https://user-images.githubusercontent.com/3083773/103584812-a7ffdb80-4ea7-11eb-862f-24dda6aa5f5b.png">

Not sure if this related to these issues: https://github.com/srophe/caesarea/issues/132 and https://github.com/srophe/caesarea/issues/133

Lastly, please note that actually having Josephus show up here is fine (see issue https://github.com/srophe/caesarea/issues/161) as long as we have the other J results too. (I was not expecting Josephus to show up, however since the J is in his second name).

**Comment by wsalesky** [comment]
@davidamichelson Okay, there are a few things going on here.
1. Not all the authors are appearing in the facets. This has now been fixed, there was an issue in how the facets were being generated. 
2. The sort by title is using the alphabetic filter on the TITLE, not the author. This creates a bit of a code conundrum for me. It will probably take me a few hours to sort it out. 

Thanks for finding these, I will let you know when I unravel the second issue.

**Comment by wsalesky** [comment]
@davidamichelson I believe both of these are now fixed. Please close if you agree.

**Comment by davidamichelson** [comment]
Looks good! Found some other issues :)
