### ISSUE TITLE
3 problems with date range drag tool in bibl module

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#163]
- [x] The tool has dynamic results which are correct on the following pages (/bibl/browse.html; bibl/browse.html?view=title&sort-element=title; and bibl/browse.html?view=date&sort-element=publicationDate) BUT has the same problem of being off by one year result as the issue in https://github.com/srophe/caesarea/issues/106

- [x] The tool does not seem to work at all (no dynamic results) when it is used on a results list from a "by date" advanced search, for example try dragging the tool here: https://caesarea-maritima.org/bibl/search.html?q=Caesarea&title=&author=&pub-place=&publisher=&start-date=1959&end-date=1961&idno= (for what it is worth the drag tool does work with other kinds of advanced search results such as keyword, title or author)

- [x] Lastly, on advanced search results pages (including date) dragging the tool uses increments of days rather than years (but on the browse results page the dragging is by years). Years instead of day/month is the best increment for our data. See this example of the day/month increments: before drag: https://caesarea-maritima.org/bibl/search.html?q=&title=Roman&author=&pub-place=&publisher=&start-date=&end-date=&idno= after drag: https://caesarea-maritima.org/bibl/search.html?startDate=1936-01-01&endDate=1997-10-28&q=&end-date=&pub-place=&author=&publisher=&start-date=&title=Roman&idno=

**Comment by wsalesky** [comment]
@davidamichelson 
For the second point the date slider still works, but only within the parameters of the search, which in this case means you can only narrow the dates, not expand them. Do you want me to change that so if you search within a date range the date slider can then override the submitted range?

**Comment by davidamichelson** [comment]
@wsalesky For number 2 and your comment, if it is not too hard, then let it override the date parameter from the original search when the user drags

**Comment by davidamichelson** [comment]
Okay it looks like the -1 on dates is fixed but it causes a display issue with the timeline. See compare the parameters (1959-1962) with the labels on the timeline/drag bar in this image
<img width="437" alt="Screen Shot 2021-01-05 at 2 15 51 PM" src="https://user-images.githubusercontent.com/3083773/103694495-a9410f00-4f60-11eb-844a-39ad1a3447aa.png">

**Comment by davidamichelson** [comment]
So could you please have the slide also show 1959-1962?

**Comment by wsalesky** [comment]
Fixed.

**Comment by davidamichelson** [comment]
Sorry One last change :)

This is small and should just change the HTML:

It makes more logical sense to change the wording on how we display the search parameter in the HTML after the search result. In the image above it puts the end date before the start date:

Current:
https://caesarea-maritima.org/bibl/search.html?q=Caesarea&title=&author=&pub-place=&publisher=&start-date=1959&end-date=1961&idno=
<img width="887" alt="Screen Shot 2021-01-06 at 9 35 46 AM" src="https://user-images.githubusercontent.com/3083773/103787080-c7f7e200-5002-11eb-8d38-ffd8b3abb9f4.png">
```10 matches for Keyword: Caesarea End date: 1961  Start date: 1959  ```

Could we please change to:
```10 matches for Keyword: Caesarea Start date: 1959  End date: 1961  ```

**Comment by wsalesky** [comment]
@davidamichelson Done. If it looks good to you please close.

**Comment by davidamichelson** [comment]
Great!
