### ISSUE TITLE
Javascript Keyboard Options

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#17]
For the keyboards dropdown menu, please put the list of languages in alphabetical order. Please add in all the languages we have available.

<img width="223" alt="Screenshot 2020-03-02 12 21 30" src="https://user-images.githubusercontent.com/3083773/75705122-5a5f8480-5c80-11ea-898b-97da2510f403.png">

**Comment by wsalesky** [comment]
@davidamichelson can you clarify what you mean by all languages? I don't know what will be included in this data, and the plugin covers 14 different languages.

**Comment by davidamichelson** [comment]
Thanks can you post the list of languages here please? We may want all 14,
I'll let you know.

**Comment by wsalesky** [comment]
- Arabic
- German
- Greek
- Spanish
- Farsi
- French
- Hebrew
- Hungarian
- Italian
- Latvian
- Polish
- Portuguese
- Romanian
- Russian
- Albanian
- Syriac

**Comment by davidamichelson** [comment]
Please include:


    Arabic
    German
    Greek
    Spanish
    French
    Hebrew
    Italian
    Polish
    Russian
    Syriac

**Comment by wsalesky** [comment]
@davidamichelson Actually, it has been a while since I updated this app, these are all the available layouts in the most recent version: 
https://github.com/Mottie/Keyboard/tree/master/layouts

**Comment by davidamichelson** [comment]
Woah, okay, well lets use the ones I put for now.

**Comment by wsalesky** [comment]
@davidamichelson Added. We can always add more as needed.
