### ISSUE TITLE
Is there some kind of index in the C-M.org app of the pleiades URIS that we need to regenerate?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#173]
There is a testimonia record that had a place with an incorrect coordinate. The record is https://caesarea-maritima.org/testimonia/163 (see image below for how it displays on the map). I changed the code (see https://github.com/srophe/caesarea-data/commit/cb2f7535f0cf229052d3135610a841d026fb6ad8 ). But even after a hard refresh the old coordinates are still on the map (in the Atlantic Ocean).
<img width="1216" alt="Screen Shot 2021-01-05 at 11 08 02 PM" src="https://user-images.githubusercontent.com/3083773/103731564-0a8dd000-4fab-11eb-929c-a4522ae603cc.png">

**Comment by wsalesky** [comment]
@davidamichelson Yes, I reran it this morning, but I will send you the link for future reference.
