### ISSUE TITLE
Testimonia Map Browse Spacing Issue in Record Preview

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#175]
In the testimonia map browse, a space is missing between the record title and the module title. See the attached screenshot; space missing between "Luke the Evangelist, 21.8-21.9" and "Textual Evidence for Caesarea-Maritima".

![Capture](https://user-images.githubusercontent.com/44096602/103777943-3a62c500-4ff7-11eb-895f-41b8fd9cff76.PNG)

**Comment by wsalesky** [comment]
Fixed.
