### ISSUE TITLE
Whitespace in WorldCat Identities URL from Bibl module

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#176]
The URLs created in the Bibl module that link to WorldCat Identities searches are inserting extra whitespace around the search string. 

Example record: https://caesarea-maritima.org/bibl/3Q7WI48R
Example URL: https://worldcat.org/identities/find?fullName=%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Felix-Marie%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Abel

FWIW, Firefox (and I'm assuming most other browsers though I haven't checked) can handle these links fine.

**Comment by wlpotter** [comment]
Sorry, spoke to soon about the links working...The links with the white space are not loading for me, but they do work without.

Compare https://worldcat.org/identities/find?fullName=%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Felix-Marie%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Abel

with https://worldcat.org/identities/find?fullName=Felix-Marie%20Abel

**Comment by wsalesky** [comment]
Fixed
