### ISSUE TITLE
Footnotes in Testimonia not linked to Bibl module records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#178]
@davidamichelson I noticed the testimonia records do not have a link to the bibl module, just to the Zotero records. I can't remember if we decided not to include those or if this is a display issue?

Compare https://caesarea-maritima.org/testimonia/48 with the Syriaca person record http://syriaca.org/person/779

**Comment by wlpotter** [comment]
@davidamichelson this might not be an issue. I'm just now remembering that we decided not to include the records tagged as "Testimonia-Works-Cited" from Zotero in the Bibl module anyway. That's why there aren't links to the bibl module...I'll leave this open just to verify that.

**Comment by davidamichelson** [comment]
Just need to document this.
