### ISSUE TITLE
Discuss Implementing Parallel Texts

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#18]
@wsalesky We would like to explore using the parallel display which you have here https://surayt.bethmardutho.org/exist/apps/e-surayt/1001 for the texts in All /TEI/text/body/ab/quote

**Comment by wsalesky** [comment]
@davidamichelson Okay, we will need some by lingual texts to test it on. You can take a look at the tei for surayt to see the underlying data structure. It should be easy to plug into the srophe app architecture.

**Comment by davidamichelson** [comment]
@wsalesky We would like to have the ability to compare the current layout with the parallel layout, could you give us two views to compare? Will will add the needed structure to the TEI and let you know when it is ready.

**Comment by wlpotter** [comment]
@wsalesky @davidamichelson I have created a branch of the data, here: https://github.com/srophe/caesarea-data/tree/testing-bilingual-parallel-texts

I've added the anchor elements on that branch.

Each anchor element is at `/TEI/text/body/ab[@type="edition" or @type="translation"]/anchor`

The `@xml:id` and `@corresp` attributes contain the data for interlinking, following the example from the Surayt Corpus, above.

Here is the relevant comit: https://github.com/srophe/caesarea-data/commit/602454d72379cf62d40ef5ab5785c1f25244fce2

I will leave the changes on the other branch for now, until we decide which way we want to proceed.

Let me know if you need anything else!

**Comment by wsalesky** [comment]
This is up: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/50

**Comment by davidamichelson** [comment]
IT looks great!

**Comment by wsalesky** [comment]
@wlpotter Can you merge this data into master? A good technique for this kind of merge is to first merge master into the branch (to catch up on all the latest changes) and then merge the branch into master.  Or let me know and I can do it.

**Comment by wlpotter** [comment]
@wsalesky I have merged the data into master, following that technique. The records on master that have both an edition and a translation should have tei:anchor elements connecting them.

**Comment by wsalesky** [comment]
Thanks, I just pulled in the updated data to my local repository and it
looks good.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Can this be closed?

**Comment by davidamichelson** [comment]
One issue to discuss today on this. The info box would appear at the bottom if there are 3+ columns.
