### ISSUE TITLE
URNs visible in Testimonia HTML

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#180]
This may be a data issue and related to https://github.com/srophe/caesarea-data/issues/39

Some records have URNs showing in the HTML beneath the text excerpts. See, for example, https://caesarea-maritima.org/testimonia/50

I think these are coming from `/TEI/text/body/ab/idno[@type="CTS-URN"]` or `/TEI/text/body/ab/ref/@target`. It looks also like the links to the external machine readable texts (Scaife, Perseus, etc.) are broken for these.

**Comment by wlpotter** [comment]
FYI this is not *just* the ones in https://github.com/srophe/caesarea-data/issues/39. See, for example, https://caesarea-maritima.org/testimonia/22

It looks like the `/TEI/text/body/ab/idno[@type="CTS-URN"]` is being displayed when it shouldn't.

**Comment by wsalesky** [comment]
Fixed
