### ISSUE TITLE
Links to the CCEL XML file

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#183]
Example record: https://caesarea-maritima.org/testimonia/90

We have two links in the Zotero records for Testimonia coming from one of the Schaff _Nicene and Post-Nicene Fathers_ volumes on the [Christian Classics Ethereal Library](https://ccel.org/). One links to the HTML page for the text from which the excerpt derives (e.g., https://ccel.org/ccel/schaff/anf07/anf07.ix.html). The other links to a download of the CCEL's XML version of that text (e.g., https://ccel.org/ccel/s/schaff/anf07.xml).

The link to the XML works fine, but it is a bit confusing to have two similar looking links which both have the hover-over text "External link to bibliographic record". Perhaps we could change the icon or hover-over text for the XML file downloads for clarity?

**Comment by davidamichelson** [comment]
We will make a new tool tip and icon for XML files

**Comment by davidamichelson** [comment]
@wsalesky I just made this change myself. I was not sure if I needed to change line 1221 or just 1264. Could you please check if I did it right and close the issue if I did please? Thanks!

**Comment by wsalesky** [comment]
@davidamichelson That looks right to me.
