### ISSUE TITLE
Zoom on Map

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#184]
@wsalesky Thanks for your work! The map reset worked. Could we change the zoom and center on the map just slightly please?

Current:
<img width="1236" alt="Screen Shot 2021-01-06 at 9 27 33 AM" src="https://user-images.githubusercontent.com/3083773/103785957-6f741500-5001-11eb-927e-2f4f93189609.png">

New:
<img width="1214" alt="Screen Shot 2021-01-06 at 9 29 25 AM" src="https://user-images.githubusercontent.com/3083773/103786133-b19d5680-5001-11eb-92a0-c4c1a639e784.png">

To achieve this I zoomed in x1 on the controller (-1) and centered on the island of Cyprus (how does the centering work? do you need coordinates for it: 35.1264° N, 33.4299° E or latitude 35.095192 longitude 33.203430)?

Thanks!

**Comment by wsalesky** [comment]
@davidamichelson How does it look now? My screen is smaller, so if it looks good on yours please close the issue.

**Comment by davidamichelson** [comment]
hmm, still shows a bit of the bad tiles. Could you please center at 35.4840483, 29.5413633 and set the zoom to +1 more?

**Comment by wsalesky** [comment]
@davidamichelson how about now?

**Comment by davidamichelson** [comment]
Perfect! @wsalesky what would we do with out you!
