### ISSUE TITLE
Faceted Browse from "About this Text" box not working

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#185]
Example record: https://caesarea-maritima.org/testimonia/48 (but this is a general issue that shows up with all the records I spot-checked)

When navigating to a faceted browse from a record's "About this Text" box, the facets don't appear to be filtering results correctly and instead display all records. These results also do not appear to be sorted in any way. I believe we would want them to sort in the same way as #71.

This issue applies to the following:

- Author, e.g. https://caesarea-maritima.org/search.html?fq=;fq-Author:http://viaf.org/viaf/25393339
- Title, e.g. https://caesarea-maritima.org/search.html?fq=;fq-Work:urn:cts:greekLit:tlg0638.tlg001
- Original Language, e.g. https://caesarea-maritima.org/search.html?fq=;fq-Original%20Language:grc
- Place Composed, e.g. https://caesarea-maritima.org/search.html?fq=;fq-Place%20Composed:https://pleiades.stoa.org/places/648801

Note also that the results list for each of these also includes all records from both the Testimonia and the Bibl modules. See, for instance, result number 137 ("The Excavations 1993-1998, 2000-2001") at https://caesarea-maritima.org/search.html?fq=;fq-Author:http://viaf.org/viaf/25393339&start=1&perpage=1048

**Comment by wsalesky** [comment]
@wlpotter I believe these are fixed. Can you please double check?

**Comment by davidamichelson** [comment]
Looks like it works! Great job!

**Comment by davidamichelson** [comment]
oops spoke to soon. Realized there is the following issue. It appears that the results here are being run at the App level and not the Module level.

I have created a branch which I think fixes this. Please review @wsalesky and merge if correct.

**Comment by wsalesky** [comment]
done!

**Comment by davidamichelson** [comment]
Yay!

**Comment by wsalesky** [comment]
Nice job!
