### ISSUE TITLE
Please merge the "publications" menu in the banner with the logo/label on the left side of the banner

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#187]
Let's discuss this am, don't change it yet.

**Comment by davidamichelson** [comment]
- [ ] Please remove the "publications menu". 
- [ ] Please remove the URL behind the logo so that clicking on the logo no longer directs one to index.html
- [ ] Please change the current module name next to the logo to a drop down menu with a caret. The text displayed in the banner should be the same as we currently have (e.g. the short names, "Caesarea-Maritima.org" or "A Collection of Testimonia" etc.) and reflect whatever page the user is on.
- [ ] The drop down menu should offer 4 options (which includes the current page that the user is on, but keep it that way so the menu is standard). The text for menu options should read and direct to in this order:

Caesarea-Maritima.org: A Digital Archive (directs to https://caesarea-maritima.org/index.html)
Caesarea Maritima: A Collection of Testimonia (directs to https://caesarea-maritima.org/testimonia/index.html)
Caesarea Maritima: A Comprehensive Bibliography (directs to https://caesarea-maritima.org/bibl/index.html)
Technical Documentation (directs to https://caesarea-maritima.org/documentation/index.html)

**Comment by wsalesky** [comment]
@davidamichelson what about the main page? If I remove the publications from there it is a pretty empty nav bar, is that okay? Should there be an about page there?

**Comment by wsalesky** [comment]
Done, but see above question above

**Comment by davidamichelson** [comment]
Thanks I like it. I changed home to about on the main index.html page.
