### ISSUE TITLE
In Testimonia: The URNs in the About This Text Box are too long and run outside the box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#189]
Example record: https://caesarea-maritima.org/testimonia/44

<img width="345" alt="Screen Shot 2021-01-06 at 10 41 48 AM" src="https://user-images.githubusercontent.com/3083773/103795747-fa5a0d00-500b-11eb-8d96-751a235440e5.png">

@wsalesky please use css to force a wrap

**Comment by wsalesky** [comment]
Fixed.
