### ISSUE TITLE
use sort by date as the default display for all search results.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#190]
Actually this issue is slightly different from what we just discussed. Are search results sorted by anything when they display? 

Currently they do not appear to be. See https://caesarea-maritima.org/bibl/search.html?q=Port&title=&author=&pub-place=&publisher=&start-date=&end-date=&idno=  Please set the default display to be by date.
or https://caesarea-maritima.org/bibl/search.html?q=&title=&author=&pub-place=&publisher=&start-date=1959&end-date=1962&idno=

So please set the default display order to be by publication date for all search results

**Comment by wsalesky** [comment]
@davidamichelson They are sorted by relevance. Do you still want the default to be by publication date?

**Comment by davidamichelson** [comment]
For the Bibl module, yes, please sort by date instead of relevance as the default and if it is not great we will role back

**Comment by wsalesky** [comment]
Done. Note to self: Not all dates fit pattern and thus do not sort correctly. Add handling for more date types. Example: 
bibl/XHRDUPIL.tei

**Comment by davidamichelson** [comment]
Interesting, do we need to analyze the data and make it uniform?

**Comment by wsalesky** [comment]
It will probably be faster for me to do it programatically. The sort dates are computed on indexing, this makes for faster much faster sorting. I can just adjust how the field generates the dates to make sure it handles the edge cases. However if you find other edge cases, let me know and I will include them. This is my next bug, after the bibl browse issue.

**Comment by davidamichelson** [comment]
Okay, it looks good but I see what you mean, if there is a month/day it does not sort those in with the by year entries. This is good enough for now, but let's leave open for you to work it out later. Thanks!

**Comment by davidamichelson** [comment]
@wsalesky Not sure about the earlier part of this issue but here is the behavior which needs fixing right now:

-[ ] Browse Bibliography by Title and then sort by Date is not working  https://caesarea-maritima.vuexistapps.us/bibl/browse.html?&start=1&sort-element=pubDate

-[ ] Browse Bibliography by Title and then sort by Creator is not working https://caesarea-maritima.vuexistapps.us/bibl/browse.html?&start=1&sort-element=creator
