### ISSUE TITLE
Changing the How to Cite in Testimonia

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#191]
Note: I fixed how the bibl module handles this. The remaining issue is for Testimonia.

Example: https://caesarea-maritima.org/testimonia/90.tei

The first short citation is fine except for one change to add italics:

Current:
Joseph L. Rife et al., “Anonymous, Apostolicae constitutiones 46,” in Caesarea Maritima: A Collection of Testimonia, last modified June 19, 2020, https://caesarea-maritima.org/testimonia/90.

New:
Joseph L. Rife et al., “Anonymous, _Apostolicae constitutiones_ 46,” in Caesarea Maritima: A Collection of Testimonia, last modified June 19, 2020, https://caesarea-maritima.org/testimonia/90.

The bibliography citation needs changing.

Current:
Bibliography:
Joseph L. Rife et al., “Anonymous, Apostolicae constitutiones 46.” In Caesarea Maritima: A Collection of Testimonia, edited by Joseph L. Rife and Phillip I. Lieberman., edited by Joseph L. Rife et al.. Caesarea City and Port Exploration Project, 2020. Entry published June 19, 2020. https://caesarea-maritima.org/testimonia/90.

New:
Rife, Joseph L., and Eliana Yonan, “Anonymous, _Apostolicae constitutiones_ 46.” In _Caesarea Maritima: A Collection of Testimonia_. Edited by Joseph L. Rife, Phillip I. Lieberman, and David A. Michelson. Technical design by David A. Michelson and William L. Potter. Nashville, TN: Caesarea City and Port Exploration Project, 2020. Entry published June 19, 2020. https://caesarea-maritima.org/testimonia/90.

Notes:

Rife, Joseph L., and Eliana Yonan = /TEI/teiHeader/fileDesc/titleStmt/editor/@role="creator"

“Anonymous, _Apostolicae constitutiones_ 46.” = /TEI/teiHeader/fileDesc/titleStmt/title/@level="a" (with italic styling for the contained m level title)

In _Caesarea Maritima: A Collection of Testimonia_. Edited by Joseph L. Rife, Phillip I. Lieberman, and David A. Michelson. Technical design by David A. Michelson and William L. Potter. Nashville, TN: Caesarea City and Port Exploration Project, 2020. = This whole part could be hard coded in. No need to pull from records.

Entry published June 19, 2020. = /TEI/teiHeader/fileDesc/publicationStmt/date

https://caesarea-maritima.org/testimonia/90 = /TEI/teiHeader/fileDesc/publicationStmt/idno/@type="URI" with trimming off the TEI

**Comment by davidamichelson** [comment]
Also need update on bibl module

**Comment by davidamichelson** [comment]
@wsalesky This is ready for you :)

**Comment by wsalesky** [comment]
@davidamichelson Let me know how it looks.

**Comment by davidamichelson** [comment]
Looks good with one tiny change still needed.

There is a trailing whitespace after the creator names and before the comma:
<img width="653" alt="space" src="https://user-images.githubusercontent.com/3083773/103910558-977b7b00-50ca-11eb-82c9-4833c0a9cff6.png">

Current:
Eliana Yonan , “Anonymous

New:

Current:
Eliana Yonan, “Anonymous

**Comment by wsalesky** [comment]
Done.
