### ISSUE TITLE
Please remove the advance one URI double arrows from both modules

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#198]
Since the URIS are not numeric this tool does not work.

<img width="651" alt="Screen Shot 2021-01-06 at 2 14 37 PM" src="https://user-images.githubusercontent.com/3083773/103815891-a9591180-5029-11eb-8d43-229910cb678c.png">

**Comment by davidamichelson** [comment]
If it is easiest we can remove them from the Testimonia module too but otherwise keep them for now in that module.

**Comment by wsalesky** [comment]
Done
