### ISSUE TITLE
Show more with long texts in Testimonia is not working as expected.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#200]
There are two, possibly related, issues.

- [ ] Some records show the "show more" button, but there is actually no "more" to show and the record already has the full text.
Example:
https://caesarea-maritima.org/testimonia/25

- [x] At least one record ends up with an odd new paragraph/line break when expanded even though there is not a new line in the XML text:
Example:
https://caesarea-maritima.org/testimonia/50

![Screen Shot 2021-01-06 at 5 23 00 PM](https://user-images.githubusercontent.com/3083773/103832488-ffd34980-5043-11eb-8254-c898915a447b.png)
![Screen Shot 2021-01-06 at 5 23 06 PM](https://user-images.githubusercontent.com/3083773/103832484-fe098600-5043-11eb-96b0-69ba2b2984ef.png)

**Comment by wsalesky** [comment]
@davidamichelson details?

**Comment by wsalesky** [comment]
Fixed

**Comment by davidamichelson** [comment]
Thanks, the second issue is fixed but the first one is not:

Some records show the "show more" button, but there is actually no "more" to show and the record already has the full text.

Example:
https://caesarea-maritima.org/testimonia/25

Any idea why the button is there but the record is not abbreviated?

**Comment by wsalesky** [comment]
Was fixed, then I overwrote the fix. Now it is really fixed. :)
