### ISSUE TITLE
Browse by Title in Bibl Module Is Actually Displaying Browse by Author

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#202]
For example:
https://caesarea-maritima.org/bibl/browse.html?lang=&alpha-filter=K&view=title

The results are all Authors beginning with K and no titles beginning with K

**Comment by davidamichelson** [comment]
oddly, I should note that Browse by Title = A does give the right results:

https://caesarea-maritima.org/bibl/browse.html?lang=&alpha-filter=A&view=title

but the other letters do not

**Comment by davidamichelson** [comment]
@wsalesky I know we sent a lot of issues this week :) thanks for your work. If you have time to do only one before tomorrow please do this one.

Thanks!

**Comment by wsalesky** [comment]
@davidamichelson next on my list!

**Comment by davidamichelson** [comment]
Thanks and sorry it has been so many requests!

**Comment by wsalesky** [comment]
No problem, it is nice to have something useful that I can actually do on a day like today. :)

**Comment by davidamichelson** [comment]
Yes!

**Comment by davidamichelson** [comment]
Saw this which motivates me to keep working:
https://twitter.com/nowviskie/status/1347193112544870400

**Comment by wsalesky** [comment]
@davidamichelson  Okay, I think this is fixed. please check and close if you agree.

**Comment by davidamichelson** [comment]
yay! Done!
