### ISSUE TITLE
Punctuation missing in abstract on browse page

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#21]
@wsalesky the rendered abstracts on the browse page (http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html) appear to be losing punctuation.

Here is the x-path for TEI source: `/TEI/text/body/desc[@type="abstract]`

For example, from the second result on the browse page:
"Caesaream and Cæsarea are place names attested in Cornelius Tacitus s The Histories 2 82 2 83 This testimonium was written circa 100..."

Should become:

"Caesaream" and "Cæsarea" are place names attested in Cornelius Tacitus's The Histories 2.82-2.83. This testimonium was written circa 100..."

**Comment by wsalesky** [comment]
@wlpotter Fixed. The spacing between quotes and commas are in the TEI and should be adjusted there.

**Comment by wlpotter** [comment]
I'm reopening this and assigning to myself to remind me to figure out the whitespace issue in the serialization from TSV into XML.
