### ISSUE TITLE
Visual tei:note[@type="corrigenda"] in Testimonia records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#214]
When a testimonia record has `/TEI/text/body/ab/note[@type="corrigenda"]`, we would like this to be labelled as a note. 

Please insert a line above this node, add a label "Note: ", and put the label and note in italics.

Example (from https://caesarea-maritima.org/testimonia/94):

Current:

“Now the third year of his reign over all Judaea had been finished when he came to the city of Caesarea, which was formerly called the tower οf strato. There he was celebrating games in honour οf Caesar, because he knew that this was a kind of feast for his safety, and at it was assembled a multitude of those in office and of high rank in the province.
Inaccuracies found in the transcription of the electronic text compared to its printed source have been corrected.
**Browse source text.**

New:

“Now the third year of his reign over all Judaea had been finished when he came to the city of Caesarea, which was formerly called the tower οf strato. There he was celebrating games in honour οf Caesar, because he knew that this was a kind of feast for his safety, and at it was assembled a multitude of those in office and of high rank in the province.

---
_Note: Inaccuracies found in the transcription of the electronic text compared to its printed source have been corrected._
 **Browse source text.**

**Comment by wsalesky** [comment]
Done.

**Comment by davidamichelson** [comment]
Yay, great work!
