### ISSUE TITLE
Work Out how to use Zotero API

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#223]
@wsalesky as mentioned we would like to make some batch changes to the Zotero data. It does appear that we could down load the entire library as JSON text and re-upload it with changes using REST: https://www.zotero.org/support/dev/web_api/v3/write_requests#updating_multiple_objects

Does that sound correct based on the above?

**Comment by wsalesky** [comment]
Yes that sounds correct. Sounds like you can also use a more targeted approach using the API, but that might be work to get set up.

**Comment by wlpotter** [comment]
@davidamichelson I don't recall which batch changes we were planning with the Zotero API? Did these get finished?
