### ISSUE TITLE
Adding "Item Type" field from Zotero to the TEI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#224]
@wsalesky We would like to visualize in the HTML the information found in the Zotero Field "Item Type".

At present there appear to be four types in our data:
Thesis 
Newspaper Article
Journal Article
Book

It looks like the xquery does process this information when preparing the TEI:
https://github.com/srophe/caesarea/blob/725fc4404029d5d50d7dc084b9a671124fe2378d/zotero2bibl/zotero2tei.xqm#L191

But we do not serialize this information into the TEI.

Please do the following:

- [ ] Task One

Include the contents of the itemType field in Zotero in the TEI as the textnode of ```<note place="inline">Item Type</note>``` at the following path: /TEI/text/body/biblStruct/monogr and place it immediately before /TEI/text/body/biblStruct/monogr/imprint[1]

Here is an example from https://caesarea-maritima.org/bibl/K76IMWWL/tei
Based on this example in the guidelines: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COBICOI

Current:
```
<biblStruct>
                <monogr>
                    <author>
                        <forename>Rivka</forename>
                        <surname>Gersht</surname>
                    </author>
                    <title level="m">The Sculpture of Caesarea Maritima</title>
                    <idno type="URI">https://caesarea-maritima.org/bibl/K76IMWWL</idno>
                    <idno type="URI">https://www.zotero.org/groups/caesarea-maritima/items/K76IMWWL</idno>
                    <idno type="URI">https://www.zotero.org/groups/2320447/items/K76IMWWL</idno>
                    <imprint>
                        <pubPlace>Tel Aviv</pubPlace>
                        <date>1987</date>
                    </imprint>
                </monogr>
            </biblStruct>
```

New:
```
<biblStruct>
                <monogr>
                    <author>
                        <forename>Rivka</forename>
                        <surname>Gersht</surname>
                    </author>
                    <title level="m">The Sculpture of Caesarea Maritima</title>
                    <idno type="URI">https://caesarea-maritima.org/bibl/K76IMWWL</idno>
                    <idno type="URI">https://www.zotero.org/groups/caesarea-maritima/items/K76IMWWL</idno>
                    <idno type="URI">https://www.zotero.org/groups/2320447/items/K76IMWWL</idno>
                    <note place="inline">Thesis</note>
                    <imprint>
                        <pubPlace>Tel Aviv</pubPlace>
                        <date>1987</date>
                    </imprint>
                </monogr>
            </biblStruct>
```

Please do this for all item types (Book, etc.).

- [ ] Task 2
Please add this information to the HTML view of the record page. It would be labeled "Type of Publication" and occur in the new ordering for the bibl page. See separate issue.

- [ ] Task 3
It appears that we do not to have a specific TEI schema for itemType "Thesis" (see the HTML for https://caesarea-maritima.org/bibl/K76IMWWL). This means that some information is being lost in the TEI transform for items of itemType "Thesis". For example in this case there is a zotero field "University" which is needed in the TEI. "University" should be treated as TEI:publisher. 

Thus the TEI would be:
New:
```
<biblStruct>
                <monogr>
                    <author>
                        <forename>Rivka</forename>
                        <surname>Gersht</surname>
                    </author>
                    <title level="m">The Sculpture of Caesarea Maritima</title>
                    <idno type="URI">https://caesarea-maritima.org/bibl/K76IMWWL</idno>
                    <idno type="URI">https://www.zotero.org/groups/caesarea-maritima/items/K76IMWWL</idno>
                    <idno type="URI">https://www.zotero.org/groups/2320447/items/K76IMWWL</idno>
                    <note place="inline">Thesis</note>
                    <imprint>
                        <publisher>Tel Aviv University</publisher>
                        <pubPlace>Tel Aviv</pubPlace>
                        <date>1987</date>
                    </imprint>
                </monogr>
            </biblStruct>
```

We might also want to try and adapt the zotero style used to render this as a Chicago style note, but let's discuss that before we do it.

**Comment by wsalesky** [comment]
@davidamichelson Done. Please close if this looks correct: 
https://caesarea-maritima.org/bibl/K76IMWWL

(I reran the zotero2bibl script, so they should all be up to date.

**Comment by davidamichelson** [comment]
Looks correct! Thank you!
