### ISSUE TITLE
Changes to Bibl Module Record Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#225]
Currently the record page HTML follows the document order of the TEI. We would like to rearrange a few items in the HTML (not the TEI). I could not figure out how to do this but would love to learn.

Specifically, we would like to do the following in the HTML.

1. Move all analytic/idno and analytic/ref down to the bottom of the list (after the monograph text notes).
2. Move the textLang and itemType (see issue https://github.com/srophe/caesarea/issues/224) to just before the idnos and refs.
3. We would also like to change the TEI tranform for Volume numbers (see issue #226)
 
Here is are two examples:

https://caesarea-maritima.org/bibl/XT3KBQU8

Current:
Full Citation Information
Article
Title: The Plurality of Harbors at Caesarea: The Southern Anchorage in Late Antiquity
Author: Alexandra L. Ratzlaff
Author: A. Yasur-Landau
Author: Ehud Galili
Author: P. Waiman-Barak
URI: https://caesarea-maritima.org/bibl/XT3KBQU8 
URI: https://www.zotero.org/groups/caesarea-maritima/items/XT3KBQU8  
See Also: https://www.worldcat.org/title/the-plurality-of-harbors-at-caesarea-the-southern-anchorage-in-late-antiquity/oclc/7107009278&referer=brief_results  
URI: http://www.worldcat.org/oclc/7107009278
Publication
Title: Journal of Maritime Archaeology
Language: English
Date of Publication: 2017
Pages: 125-146
Volume: 12

New:
Current:
Full Citation Information
Article
Title: The Plurality of Harbors at Caesarea: The Southern Anchorage in Late Antiquity
Author: Alexandra L. Ratzlaff
Author: A. Yasur-Landau
Author: Ehud Galili
Author: P. Waiman-Barak
Publication
Title: Journal of Maritime Archaeology
Date of Publication: 2017
Volume: 12
Pages: 125-146
Publication Type: Journal Article
Language: English
URI: https://caesarea-maritima.org/bibl/XT3KBQU8 
URI: https://www.zotero.org/groups/caesarea-maritima/items/XT3KBQU8  
See Also: https://www.worldcat.org/title/the-plurality-of-harbors-at-caesarea-the-southern-anchorage-in-late-antiquity/oclc/7107009278&referer=brief_results  
URI: http://www.worldcat.org/oclc/7107009278

Example 2
https://caesarea-maritima.org/bibl/BNG97Q7Z

Current:
Full Citation Information
Publication
Title: For Uriel: Studies in the History of Israel in Antiquity Presented to Professor Uriel Rappaport
Editor: Menahem Mor
URI: https://caesarea-maritima.org/bibl/BNG97Q7Z 
URI: https://www.zotero.org/groups/caesarea-maritima/items/BNG97Q7Z
See Also: https://www.worldcat.org/oclc/745378221&referer=brief_results  
Language: Hebrew
Place of Publication: Jerusalem
Publisher: Zalman Shazar Center
Date of Publication: 2005

New:
Full Citation Information
Publication
Title: For Uriel: Studies in the History of Israel in Antiquity Presented to Professor Uriel Rappaport
Editor: Menahem Mor
Place of Publication: Jerusalem
Publisher: Zalman Shazar Center
Date of Publication: 2005
Publication Type: Book
Language: Hebrew
URI: https://caesarea-maritima.org/bibl/BNG97Q7Z 
URI: https://www.zotero.org/groups/caesarea-maritima/items/BNG97Q7Z
See Also: https://www.worldcat.org/oclc/745378221&referer=brief_results

**Comment by wsalesky** [comment]
@davidamichelson 
There are two ways to change order of the TEI elements display, depending on how much you want to change. 

1.  Easy option, not as fine grade control. 
Change this: 
https://github.com/srophe/caesarea/blob/master/bibl/record.html#L9
to something like this (just an example for any TEI): 
```
<div data-template="app:display-nodes" data-template-paths="/descendant::tei:body/descendant::note[@type='abstract']"/>
<div data-template="app:display-nodes" data-template-paths="/descendant::tei:body/descendant::tei:analytic"/>
<div data-template="app:display-nodes" data-template-paths="/descendant::tei:body/descendant::monogr"/>
```

2.  More granular control, edit the XSLT. In this case I will edit here to specify the order: 
https://github.com/srophe/caesarea/blob/master/resources/xsl/bibliography.xsl#L1379

**Comment by wsalesky** [comment]
@davidamichelson How does this look?

**Comment by davidamichelson** [comment]
Great and thanks for the tutorial!
