### ISSUE TITLE
Change order of biblScope pages and vol in zotero2tei

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#226]
We would like the bibleScope unit="vol" to occur before biblScope unit="pp" in the TEI document order.

**Comment by wsalesky** [comment]
Done, will leave open until tested.

**Comment by davidamichelson** [comment]
hmm, didn't work: https://caesarea-maritima.org/bibl/3Q7WI48R

Any ideas?

**Comment by davidamichelson** [comment]
or here: https://caesarea-maritima.org/bibl/9L3EA58Z

**Comment by wsalesky** [comment]
Did you rerun the zotero2bibl script? The records have to be regenerated.

**Comment by davidamichelson** [comment]
Oh right! I forgot about that, will do in AM

**Comment by wsalesky** [comment]
@davidamichelson I reran the data locally to test the addition of the item type and this one is working as expected.

**Comment by wsalesky** [comment]
By then I will have finished the itemType so either I will run it tonight when I'm done, or you can run it in the am if I don't get to it. I will let you know.

**Comment by wsalesky** [comment]
@davidamichelson I reran the zotero2bibl script, so you do not need to.
