### ISSUE TITLE
Add "Historical Era Composed" to info box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#23]
Please add "Historical Era Composed" to the info box, underneath the line "Date Composed" use  TEI/teiHeader/profileDesc/creation/origDate/@period and then draw the values from classDecl/taxonomy/@xml:id="CM-NEAEH" to fill in this  item. Note some texts will have more than one @ value

Example from: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/50

    Date Composed: 380 – 391 CE
    Historical Era Composed: Byzantine Period, 324-638 CE (this is then a link to a browse faceted to just this era)
    Place Composed:Rome
    Original Language:Latin
    Author:Ammianus Marcellinus
    Title:History
    Citation:14.11
    URN:urn:cts:latinLit:stoa0023.stoa001:14.11

**Comment by davidamichelson** [comment]
Note, maybe you will want to always force the name of the period on to a new line?

Example from: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/50

    Date Composed: 380 – 391 CE
    Historical Era Composed: 
       Byzantine Period, 324-638 CE
    Place Composed:Rome
    Original Language:Latin
    Author:Ammianus Marcellinus
    Title:History
    Citation:14.11
    URN:urn:cts:latinLit:stoa0023.stoa001:14.11

**Comment by wsalesky** [comment]
Updated. Close if it looks good.

**Comment by davidamichelson** [comment]
Thanks! Looks good but there was one misunderstanding.

We want the box to have BOTH Date Composed and Historical Era Composed

See above or below:

   Date Composed: 380 – 391 CE
   Historical Era Composed: 
      Byzantine Period, 324-638 CE

On http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/50

the following is missing


   Date Composed: **_380 – 391 CE
   Historical Era Composed:_** 
      Byzantine Period, 324-638 CE

**Comment by wsalesky** [comment]
Opps! I fixed it. :)
