### ISSUE TITLE
Bibl Module: Please add Item Type as a Facet below Date on the Lefthand Menu of Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#232]
This issue looks great: https://github.com/srophe/caesarea/issues/224

- [x] Now can we add this as a facet feature on Browse please?

- [ ] Let's also add it as a radio box choice (with the four options: Book, Journal Article, Newspaper Article, Thesis) in advanced search.

**Comment by davidamichelson** [comment]
@wsalesky Looks great, could you please also add it as a radio box choice (with the five options: Book, Book Section, Journal Article, Newspaper Article, Thesis) in advanced search for bibl?

**Comment by wsalesky** [comment]
@davidamichelson added to search.

**Comment by wsalesky** [comment]
Done
