### ISSUE TITLE
We need advice on trailing slash with URLs

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#234]
See this tweet for a short version of the question: https://twitter.com/JohnMu/status/943076424130363392

We have discovered that a trailing slash at the end of a VIAF URI does create a problem in the app.

We also have some trailing slashes in the TEI:editorialDecl which has no effect (since there is no processing on that data). But perhaps we should normalize.

@wsalesky lets discuss.

**Comment by davidamichelson** [comment]
Related https://github.com/srophe/caesarea-data/issues/61

**Comment by wsalesky** [comment]
@davidamichelson I think it is a good idea to remove trailing slashes, just in terms of clean data, but where does it cause problems with the app?

**Comment by davidamichelson** [comment]
@wlpotter please make a search and destroy issue in data repository.
