### ISSUE TITLE
Remove "Bibliography" Header in Testimonia App and Visualize TEI:Head instead

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#235]
Related to: https://github.com/srophe/caesarea-data/issues/62

When there is a body/listBibl/head/text(), please create a heading from that textnode at the head of each listBibl.

**Comment by davidamichelson** [comment]
@wlpotter When you have changed the data, please let @wsalesky know so she can make these changes.

**Comment by wlpotter** [comment]
@wsalesky the data should be ready to go for these changes.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter my brain seems to be moving a little slowly today, can you remind me what needs to happen here, maybe with screen shots and an example record. 
Thanks!

**Comment by wlpotter** [comment]
@wsalesky sure thing! Example record: https://caesarea-maritima.org/testimonia/43

Currently the app is creating a heading for the bibliographic section, as seen in the screenshot:

![image](https://user-images.githubusercontent.com/44096602/105242952-fbbf2580-5b33-11eb-8223-1c2700c41ca4.png)


----

We would like to delete that heading and instead display the text node of each tei:listBibl element's tei:head (full xpath: `/TEI/text/body/listBibl/head/text()`)

These two headings (one under each listBibl) can be styled in the same way the "Bibliography" heading that they're replacing is.

So, based on the example above, this should end up like:

>**Works Cited**
>
>1 Pliny the Elder, Naturalis Historia: Machine Readable Text, ed. Karl Friedrich Theodor Mayhoff (Medford, MA: Trustees of Tufts University, 2016), section: 5.13.
>2 Pliny the Elder, The Natural History: Machine Readable Text, trans. John Bostock and H.T. Riley (Medford, MA: Trustees of Tufts University, 2004), section: 5.13.
>
>**Additional Bibliography**
>
> Pliny the Elder, Naturalis historia, ed. Karl Mayhoff (Stutgardiae: B.G. Teubner, 1906)., section: 5.13.Link to Zotero Bibliographic Record
>Pliny the Elder, The Natural History of Pliny. Tr., with Copious Notes and Illustrations, by the Late John Bostock and H.T. Riley, trans. John Bostock and H.T. Riley (London: Taylor and Francis, 1855), section: 5.13.

**Comment by wsalesky** [comment]
Done.

**Comment by davidamichelson** [comment]
@wsalesky We think we found another feature that was lost in January 21. We are re-opening this issue. Could you please see if you can find this code and make this feature return? Thanks!

**Comment by wsalesky** [comment]
Done
