### ISSUE TITLE
Timeline browse by Historical Period

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#24]
Can you set the timeline up to have facet by period?

That would be preferable to 
the following option when one clicks on the Historical Period Composed in the info box in a record:
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html?view=timeline&slideID=https://caesarea-maritima.org/testimonia/50/tei

Also when one browses by period, please have the timeline set the start and end date of it's display to the period's start and end dates. Thus for Byzantine Period, 324-638 CE

**Comment by wsalesky** [comment]
I will see what I can do.

**Comment by wlpotter** [comment]
@wsalesky For the start and end dates, I have a TSV file that relates each period's xml:id value with a start and end date. I can send you the TSV, or is there a better machine-actionable format you would like it in?

**Comment by wsalesky** [comment]
Can you put it in xml?

**Comment by wlpotter** [comment]
Here is a link to the xml: https://gist.github.com/wlpotter/ffc6c80d34c35e989dcf035d7f0bdab5

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter 
Do you want this to appear on the side like the facets? Do you want all the time periods to show up in the list, or only the ones with data?

**Comment by davidamichelson** [comment]
Hmm, not sure let's discuss, definitely we only wnat the ones that have Data to be an option, not the full list

**Comment by davidamichelson** [comment]
Add buttons to limite/focus timeline by date range for the historical periods

**Comment by wsalesky** [comment]
@wlpotter Do you think you could add another column to the data here: https://gist.github.com/wlpotter/ffc6c80d34c35e989dcf035d7f0bdab5 

Just a reader friendly version of the dates to add to the display labels. ex: 36 BCE-70 CE

**Comment by wlpotter** [comment]
@wsalesky I have added a column "dateRangeLabel" with the requested reader friendly version of the dates. (I updated the gist directly: https://gist.github.com/wlpotter/ffc6c80d34c35e989dcf035d7f0bdab5)

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson  How does this look?
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html?view=timeline

**Comment by davidamichelson** [comment]
Looks great and FYI the timeline now stretches full screen on 27 inch display.
