### ISSUE TITLE
Tighten Up Whitespace Inside the Module Boxes on the Homepage

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#241]
@wsalesky Can we try and remove some of the whitespace inside the module boxes on the main index page?

**Comment by wsalesky** [comment]
@davidamichelson Yes, I think that is a CSS min-height, in an effort to keep them the same height.

**Comment by davidamichelson** [comment]
Would it be possible to reduce the min height at all?

**Comment by wsalesky** [comment]
@davidamichelson Yes I think so, it is less of a problem now that the buttons are not at the bottom. I will try to get to it tonight, should be an easy fix.

**Comment by wsalesky** [comment]
@davidamichelson How is this?

**Comment by davidamichelson** [comment]
Looks great!
