### ISSUE TITLE
Did I corrupt the code?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#246]
@wsalesky I made an update by adding two files, but somehow 12 files are also changed: https://github.com/srophe/caesarea/commit/81acfebafaa7991acbf070574fde5bfa47bd8467

Did I somehow merge in an old version of the code?

Sorry!

**Comment by wsalesky** [comment]
@davidamichelson Those additional changes are changes I made, I'm not sure why the changes are showing up with your pull request, but they are all what should be on the master branch. Always remember to pull the master branch before creating a new branch. Also it is good practice to merge the master branch into your new branch before pushing the new branch, this will keep them in syn, if you are working on a single branch over a few days. Do you see any issues on the server?

**Comment by davidamichelson** [comment]
Thanks!
