### ISSUE TITLE
Restructure to Two Modules

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#25]
Hi Winona, great work so far! Now that I see the app I think we want to structure the web app as two modules in the following way:

Site = Caesarea-Maritima.org (corresponds to Syriaca.org)

Module 1 = Caesarea Maritima: A Thesaurus of Testimonia (corresponds to SBD, in Syriaca)

Module 2 = Caesarea Maritima: A Comprehensive Bibliography (corresponds to how Syriaca.org's bibliography is becoming a standalone module)

Can you work the homepage to reflect the presence of two modules this way please? Then each module needs a homepage as well.

**Comment by wsalesky** [comment]
Done. Will need to make them pretty at some point.

**Comment by davidamichelson** [comment]
Great! You wrote: "Will need to make them pretty" @wlpotter is in fact working on images for you for them ;)
