### ISSUE TITLE
Improvement to handling of TEI:biblScope + TEI:citedRange in body/listBibl/bibl at the end of testimonia records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#250]
@wsalesky There is something that ends up looking odd when the app brings over TEI data from the Bibl Module in to the Testimonia module.

Currently some testimonia records have citedRange data as in this example from 139:
```
<bibl>
<ptr target="https://caesarea-maritima.org/bibl/R8Y9YB8L"/>
<citedRange unit="section">75</citedRange>
</bibl>
```
The bibl records have this:
```
<monogr>
<editor>
<forename>Henry</forename>
<surname>Wace</surname>
</editor>
<editor>
<forename>Philip</forename>
<surname>Schaff</surname>
</editor>
<title level="m">
Theodoret, Jerome, Gennadius, & Rufinus: Historical Writings
</title>
<note place="inline">bookSection</note>
<textLang mainLang="en"/>
<imprint>
<pubPlace>New York</pubPlace>
<publisher>Christian Literature Publishing</publisher>
<date>1892</date>
</imprint>
<biblScope unit="pp">359-384</biblScope>
</monogr>
```
The TEI here is good and fine for both.

When the Testimonia app does it's thing, however, there is a bit of a crunch in the mashup:

The result looks like:
Jerome, Lives of Illustrious Men, in Theodoret, Jerome, Gennadius, & Rufinus: Historical Writings, ed. Henry Wace and Philip Schaff, Nicene and Post-Nicene Fathers. 2nd Series 3 (New York: Christian Literature Publishing, 1892), 359–84., section: 75.

the problem bit is here: ```359–84., section: 75.```

Instead of the comma, could you have the citation look like this:
...Literature Publishing, 1892), 359–84. See section: 75.

**Comment by davidamichelson** [comment]
So instead of the comma insert whitespace and the word "See"

**Comment by davidamichelson** [comment]
This is the test records: https://caesarea-maritima.org/testimonia/139

**Comment by wsalesky** [comment]
Fixed
