### ISSUE TITLE
fixing spaces in texts on the homepage or launch-page

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#251]
Hi folks. Two related things here:
1) I noticed there are some misplaced commas/spaces around the site names in right-to-left scripts on the cover page: "... scholarship about the historic settlement of Caesarea Maritima (Καισάρεια, Caesarea Palestinae, قيسارية, קֵיסָרְיָה, ܩܣܪܝܐ, Keisarya or Qaysaria) on the Mediterranean coast ..." Or maybe I am wrong and I dont know how spaces and commas work in right-to-left scripts?
2) In terms of the order of place names in different languages, let's fix so that it goes: Greek, Latin, Hebrew, Syriac, Arabic, then the transliterated modern ones. Does that sound good? that would be historical. looked to me like Syriac preceeded Hebrew as it now stands.
thx!

**Comment by wlpotter** [comment]
I believe number 1 is an app issue, but number 2 is a data issue. Splitting the data issue to https://github.com/srophe/caesarea-data/issues/91

**Comment by wlpotter** [comment]
@davidamichelson I think you can edit the text on the app? Looks like an HTML change

**Comment by wlpotter** [comment]
Ah, I misunderstood...This is all for the home page list of names...

**Comment by davidamichelson** [comment]
FIXED BY https://github.com/srophe/caesarea/pull/268 and https://github.com/srophe/caesarea/pull/269

**Comment by wlpotter** [comment]
@wsalesky @davidamichelson the index and about pages look correct
