### ISSUE TITLE
adjusting section ref for sources in data form; and date

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#252]
Hi Will -- sorry toi keep monkeying with this! Can we make two more small adjustments to the data form?
1) Under dates: Let's add "Classical Period (480-336 B.C.E.)" or whatever format we use in English. I know this overlaps with other periods alreayd there, but we have others that overlap; and it is such a pervasive period-designation for Greek authors.
2) Under the place where there is a pull-down menu and there are different kinds of unit for dividing text: Can we make sure we include the following options: book, chapter, section, entry, letter (Adding those will maximize options and cover I think all base)
thanks! J

**Comment by wlpotter** [comment]
Migrated to https://github.com/srophe/caesarea-data/issues/90
