### ISSUE TITLE
add new chronological period to taxonomy

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#253]
Add the following period: 

```
<category xml:id="classicalPeriod">
    <catDesc>Classical Period, 480-336 BCE</catDesc>
</category>
````
for the app

@wsalesky I will add this period to [this file](https://github.com/srophe/caesarea/blob/master/documentation/caesarea-maritima-historical-era-taxonomy.xml). Are there any other changes to the app that need to be made?

**Comment by wsalesky** [comment]
@wlpotter That should be fine. Let me know if it does not behave as expected.

**Comment by wsalesky** [comment]
@wlpotter Are there any actions I need to take on this?

**Comment by wlpotter** [comment]
@wsalesky I think it is working, though I'm not sure we have that period in our data yet. I think the only change that might happen is in connection with #256 . 

I think this issue can be closed though
