### ISSUE TITLE
adding a couple "additional bibliography" to dataform

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#254]
On the current version of the data-entry form for testimonia, we only have two places for additional bibliography -- could we add two more for four total?  many thanks  Joe

**Comment by josephrife** [comment]
well I am not sure whether this is necessary -- the limited number of additional bib options seems to be a feature of the earlier version of the data entry form, but I am going back and editing some old testimonia records already on the web, and when I open the tei files they all open in the older version of the data-entry form, not the newest one (hmm)

**Comment by wlpotter** [comment]
Moved to https://github.com/srophe/caesarea-data/issues/94
