### ISSUE TITLE
erase testimonium (yikes! but yes)

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#255]
Hi folks. I am finding a few testimonia that made it into the original listing in the Word docx that I gave you, but as you saw it was a rough draft, and I had read all the passages myself. A few of them are not in fact testimonia about Caesarea. We should erase those. ONe is Jerome on Hilary of Poitiers:
Jerome, De viris illustribus 100 are place names attested in Jerome's De viris illustribus 100. This testimonium was written circa 392 CE. This work was likely written in Bethlehem.URI: https://caesarea-maritima.org/testimonia/141
I will send along requests for erasure of a few more as I come across them. I know this sounds drastic but if you check it out you will see,  Joe

**Comment by wlpotter** [comment]
Moved to https://github.com/srophe/caesarea-data/issues/93
