### ISSUE TITLE
fixing date for British Mandate admin in chronology for testimonia

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#256]
Hi folks in the chronology for dating testimonia, let's fix the one that currently reads "British Territorial Administration Period 1970-1920 CE" to "British Territorial Administration 1917-1920" thx

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter I can make this change if you like. However while looking at the taxonomy, I noticed there are many other time periods that follow the above format, should they all be changed? i.e. remove 'Period' and 'CE' from the labels?

**Comment by wlpotter** [comment]
@wsalesky @davidamichelson we can update the [historical-era-taxonomy file](https://github.com/srophe/caesarea/blob/master/documentation/caesarea-maritima-historical-era-taxonomy.xml) with the changes, though we may want to get confirmation from the editors on how they would like the labels to appear.

Note to self: this will require a data issue as well to update the tei:taxonomy in records' teiHeader.

**Comment by wlpotter** [comment]
Data issue split off to https://github.com/srophe/caesarea-data/issues/92

**Comment by josephrife** [comment]
Hi all -- my bad, there was a typo in my message--the years dates do need CE after them, so it should be "British Territorial Administration: 1917-1920 CE." So erase "Period" ('administration' already connotes a period of time, cf. "Kingdom" in earlier periods); and fix the date from 1970 to 1917. many tyhx

-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by josephrife** [comment]
All the periods/dates, once the British Territorial Administration is fixed, are fine .., except that I am not sure about "Iron IIC: 799-731 BCE" which seems off-- Will, was defined borrowed from somewhere e.g. the Anc Near East encyclopedia? many thx

-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by wlpotter** [comment]
This has been fixed in data and [here](https://github.com/srophe/caesarea/blob/master/documentation/caesarea-maritima-historical-era-taxonomy.xml). I believe this is fixed but am leaving open to test

**Comment by wlpotter** [comment]
FYI, It looks like the data needs to be re-uploaded to the server? The data fix mentioned in this issue is fixed on GitHub but is still wrong on the server (both on production and the VU dev app).

**Comment by wsalesky** [comment]
@wlpotter Is the data on the server up to date now? If so, please close, if not I will reload it.

**Comment by wlpotter** [comment]
@wsalesky yes, the data is up to date, so this issue can be closed.
