### ISSUE TITLE
languages to adding for classifying testimonia

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#259]
Can we add to the list of languages as options in the drop-down menu on the date-entry form--and thus in general I suppose we are adding languages as identifiers for testimonia: The four languages to add are 1) Old Provençal ; 2) Norman French ; 3) Ge'ez (Classical Ethiopic) ; 4) Coptic -- many thanks, Joe

**Comment by davidamichelson** [comment]
https://www.loc.gov/standards/iso639-2/php/code_list.php

pro |   | Provençal, Old (to 1500);Occitan, Old (to 1500) | provençal ancien (jusqu'à 1500); occitan ancien (jusqu'à 1500)
-- | -- | -- | --

**Comment by davidamichelson** [comment]
-- | -- | -- | --
cop | Coptic | copte | Koptisch
gez | Geez | guèze | Altäthiopisch
pro | Provençal, Old (to 1500);Occitan, Old (to 1500) | provençal ancien (jusqu'à 1500); occitan ancien (jusqu'à 1500)
-- | -- | -- | --

**Comment by wlpotter** [comment]
FYI, this has been added to the data template's CSS so the author-mode form should include these languages for data entry. Not sure if anything else is needed here?

**Comment by wlpotter** [comment]
@davidamichelson does anything on the app need to change for updating the list of possible languages?
