### ISSUE TITLE
Update/add banner photos for main and sub modules

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#26]
See issue #25 

I am attaching the two banner photos for the site (Caesarea-Maritima.org, which corresponds to Syriaca.org, currently at http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/index.html); and for the Thesaurus of Testimonia sub-module (currently at http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/index.html). 

Below are drafted captions for these two images. @davidamichelson please edit these as needed and then assign the issue to @wsalesky to update the app.

1. Site: Caesarea-Maritima.org (the image is an aerial photo of the city). 
- Caption/alt-text: "Aerial photo of Caesarea Maritima"
- Copyright information: "Original photo created by Meronim, copyright 2013, and published by [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:WikiAir_Flight_IL-13-02_1083.JPG). This photo was taken as part of WikiAir in Israel, in cooperation with The Israeli Association of General Aviation. Pilot: Eli Inbar. Flight Code: IL-13-02.
The image has been cropped and reused here under the terms of the [Creative Commons Attribution-Share Alike 3.0 Unported license](https://creativecommons.org/licenses/by-sa/3.0/)."

![WikiAir_Flight_IL-13-02_1083-cropped](https://user-images.githubusercontent.com/44096602/77327715-9d45d280-6ce9-11ea-8753-0e6897a8b00e.JPG)

2. Module 1: Thesaurus of Testimonia (the image is of a pre-modern map)
- Caption/alt-text: "Detail from a facsimile of Tabula Peutingeriana, 1-4th century CE."
- Copyright information: "Public domain image, originally published in Miller, Konrad and Castorius. _Castori Romanorum cosmographi tabula quae dicitur Peutingeriana_. Ravensburg: Otto Meier, 1887. Full image is available [here](http://urn.fi/URN:NBN:fi-fe201302081796).
The image has been cropped and reused here under the terms of the [Creative Commons Universal Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/)."
![Tabula_Peutingeriana_-_Miller_CroppedToCaesareaMaritima](https://user-images.githubusercontent.com/44096602/77327709-9b7c0f00-6ce9-11ea-8b63-f3dcefdc186b.jpg)

We have not decided yet on an image for the Bibliography sub-module. I will add the information for that module to this issue when available.

**Comment by davidamichelson** [comment]
Please find a cool schematic from an early 20th C or 19th century excavation report

**Comment by wlpotter** [comment]
@davidamichelson  I found a schematic of Caesarea's aqueduct that could work. Here is the cropped version:
![caesarea-aqueduct-schematic-Conder-1881-Cropped](https://user-images.githubusercontent.com/44096602/77771681-ff1d7980-7014-11ea-8923-76dd2041aff7.jpg)

- Caption/alt-text: "Nineteenth-century schematic of the aqueduct at Caesarea Maritima."
- Copyright information: "Public domain image, originally published in Conder, Claude Reignier. _The Survey of Western Palestine. Memoirs of the Topography, Orography, Hydrography, and Archaeology. Vol. 2_. London: Committee of the Palestine Exploration Fund, 1882.
The image has been cropped and reused here under the terms of the [Creative Commons Universal Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/)."

We have this in our bibl module. Should we link to it?

There were other interesting images, but I had trouble cropping them to the right dimensions. I can take another crack at it if need be, though.

**Comment by davidamichelson** [comment]
Great, that works well. Include a link to the work URI in the citation :)

**Comment by davidamichelson** [comment]
Also do link here to the other interesting items and Winona can apply her
magic to them if need be.

**Comment by davidamichelson** [comment]
One option might be a collage which would evoke the idea of a bibliography

**Comment by davidamichelson** [comment]
I like the maps in this book that are a couple pages before the aqueduct,
Winona can you look through pages 14-19 and see what you might use or
combine to make something visually interesting?
https://archive.org/details/surveyofwesternp02conduoft/page/n31/mode/2up/search/Herod

**Comment by wlpotter** [comment]
Here is an updated version of the caption and copyright for the aqueduct image:


- Caption/alt-text: "Nineteenth-century schematic of the aqueduct at Caesarea Maritima."
- Copyright information: "Public domain image, originally published in Conder, Claude Reignier. _The Survey of Western Palestine. Memoirs of the Topography, Orography, Hydrography, and Archaeology. Vol. 2_. London: Committee of the Palestine Exploration Fund, 1882, p. 14. https://caesarea-maritima.org/bibl/8LK45VN9
The image has been cropped and reused here under the terms of the [Creative Commons Universal Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/)."

**Comment by wlpotter** [comment]
The top left drawing on page 20 of this work, https://archive.org/details/gri_33125009339611/page/n45/mode/2up, is an 18th c map of Caesarea.

Here is a late 19th c drawing of a statue from Caesarea: (p. 156) https://archive.org/details/archaeologicalre02cler/page/156/mode/2up

And here (https://archive.org/details/archaeologicalre02cler/page/2/mode/2up), on p. 2 there is a drawing of what the author calls an "ancient mask from Caesarea"

**Comment by davidamichelson** [comment]
@wsalesky Okay, please just use the first image for now (schematic of Caesarea's aqueduct) and let's wait on input from the editors before doing anything more elaborate. Thanks!

**Comment by wsalesky** [comment]
Updated.

**Comment by davidamichelson** [comment]
Looks great! Thanks!

**Comment by wlpotter** [comment]
@wsalesky we are ready to move forward with creating a collage for the Bibl moudle's banner page (this will replace the aqueduct schematic that is currently [here](http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/index.html)).

Could you take images from the links compiled below and work them into a visually interesting collage that makes clear that this module is about modern bibliographic sources related to Caesarea?

- the maps on pages 14-19 of this source (can include the aqueduct schematic as well, which is on page 19): https://archive.org/details/surveyofwesternp02conduoft/page/n31
- The top left drawing on page 20 of this work, https://archive.org/details/gri_33125009339611/page/n45/mode/2up, is an 18th c map of Caesarea.
- Here is a late 19th c drawing of a statue from Caesarea: (p. 156) https://archive.org/details/archaeologicalre02cler/page/156/mode/2up
- And here (https://archive.org/details/archaeologicalre02cler/page/2/mode/2up), on p. 2 there is a drawing of what the author calls an "ancient mask from Caesarea"

**Comment by davidamichelson** [comment]
@wsalesky Please do take a shot at making a collage using these images.

**Comment by davidamichelson** [comment]
Let's just leave the image we have for now.
