### ISSUE TITLE
Refresher on How to Push Zotero to the Srophé DB

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#260]
@wsalesky Can you please write up refresher with instructions on this for us? Thanks!

**Comment by davidamichelson** [comment]
@wsalesky quick question about ...zotero2bibl/index.html

After a new deployment of a docker image, do we need to edit the zotero-config.xml ? The instructions mention say to do so on the link above. But looking at the file it seems already up to date.

All we need to do is run the initiate for the first time, correct?

**Comment by wsalesky** [comment]
I think I coded the correct info into the zotero config file that gets loaded into the docker image, as there are no passwords required. So you should be good to go. The current docker image also loads with bibl records preloaded, but it may not be the most up to date. So you will have to do update, or if that is not catching everything you can run initiate.
