### ISSUE TITLE
Deploy New Version of the App to resolve issues

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#265]
@wsalesky 

Please deploy the new version as we discussed to resolve these issues from @wlpotter 

Thanks!
Dave

               - Bibl browse faceting by date range was not working (e.g. https://caesarea-maritima.vuexistapps.us/bibl/browse.html?startDate=1781-07-02&endDate=1966-06-17)
               - sorting (in bibl or testimonia browse) by author or title is not working (e.g. https://caesarea-maritima.vuexistapps.us/testimonia/browse.html?&start=1&sort-element=title)
               - faceting in testimonia or bibl browse by author name not working (e.g. https://caesarea-maritima.vuexistapps.us/testimonia/browse.html?lang=&alpha-filter=J)
               - Testimonia browse-by-timeline not working (e.g. https://caesarea-maritima.vuexistapps.us/testimonia/browse.html?view=timeline&fq=;fq-Historical%20Era%20Composed:%23herodian)
               - Testimonia browse-by-map not working (two records appear from Josephus, but the underlying tile doesn't load, and I believe we have more than two mappable records. See https://caesarea-maritima.vuexistapps.us/testimonia/browse.html?view=map)

**Comment by wsalesky** [comment]
The app has been updated, there are issues with deploying the new docker. I will get back to you on those when I have a few hours for testing.

**Comment by wsalesky** [comment]
fixed
