### ISSUE TITLE
Browse Bibliography by Title Publication Date Facets are in Frequency Order, Change to Abbreviated Alpha Order

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#266]
Currently, the Publication Date Facets on Browse Bibliography by Title https://caesarea-maritima.vuexistapps.us/bibl/browse.html?&start=1&sort-element=creator are listed in order of greatest to least frequency. 

We would like to change their display order to be similar to Author facets on the same page.

i.e. The abbreviated listing shows the top 5 results in alphabetical order and then the "view all" shows all results in alphabetical (not frequency) order

**Comment by wsalesky** [comment]
Fixed. For reference, this can is controlled here: https://github.com/srophe/caesarea/blob/master/bibl/facet-def.xml#L7

Also, the current facet, just lists does not group dates into decades, if you want to do that to condense the list let me know. Example here: https://github.com/srophe/caesarea/blob/master/bibl/facet-def.xml#L23
