### ISSUE TITLE
Map browse for Caesarea Maritima Testimonia module

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#27]
Splitting off the discussion of map browse from the more general issue #6

**Comment by davidamichelson** [comment]
Please add filter to the map, similar to BQ, include all the facet options that are available in the All Browse

**Comment by wsalesky** [comment]
Added filters. @wlpotter @davidamichelson  Please review and close if you approve.

**Comment by wsalesky** [comment]
@wsalesky Rerun the Place Data.

**Comment by wsalesky** [comment]
@davidamichelson  I think the data is correct, this is the data given by Pleiades. If you look at their map, the point is in the ocean as well. We can hand code it if you would rather? 

https://pleiades.stoa.org/places/991396/json
https://pleiades.stoa.org/places/991396

**Comment by wlpotter** [comment]
@wsalesky sorry, we weren't clear on this. We replaced that Pleiades URI in the testimonia XML so that the records associated with Palestine point to this URI: https://pleiades.stoa.org/places/687995. (Cf. [this issue](https://github.com/srophe/caesarea-data/issues/9) and associated [commit](https://github.com/srophe/caesarea-data/commit/8b4f8e02764f67ecb48ae717eb3e30f158a528f0))

I think the testimonia data itself needs to be updated on the server?

**Comment by wsalesky** [comment]
Fixed!
