### ISSUE TITLE
Discuss Zotero to Chicago Note Rendering 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#282]
@wsalesky There seems to be a problem with the Zotero stylesheets. Let's discuss on Thursday. Thanks.

**Comment by wlpotter** [comment]
Example https://caesarea-maritima.org/testimonia/133

**Comment by davidamichelson** [comment]
Solution = strip trailing period from Zotero API's citation before formatting.

**Comment by wsalesky** [comment]
Fixed
