### ISSUE TITLE
Update Bibl module entry contributor names coming from Zotero Usernames

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#284]
see, e.g., https://caesarea-maritima.org/bibl/3Q7WI48R.

"Joshua_Woods" should become "Joshua Woods"

"itsbiaancaa" should become "Bianca Gardner"

"elianayonan" should become "Eliana Yonan" (I'm not sure any of these will appear in the Bibl module as she worked primarily on the bibls for the Testimonia)

related to https://github.com/srophe/caesarea-data/issues/18

I'm not sure if we ever figured out how the best way to convert the Zotero ID to an editors.xml ID. This may need an App issue as well.

**Comment by davidamichelson** [comment]
@wsalesky Please implement this new look up table.

**Comment by wsalesky** [comment]
This has been fixed. And the data has been updated.
