### ISSUE TITLE
Some links in About this Testimonia Not Working as Faceting, Seem to be pointing to the app as a whole, not the module

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#289]
Example record: https://caesarea-maritima.org/testimonia/136

The following 4 are not working (they just take the user to a browse by page but with no facet data). 

They seem to be operating on the app as a whole and not on the testimonia module level.

- [ ] Author:Theophanes the Confessor
This points to: https://caesarea-maritima.org/search.html?fq=;fq-Author:http://viaf.org/viaf/54944687&all-author=on

This should point to 
- [ ] Title:[Chronicle](https://caesarea-maritima.org/search.html?fq=;fq-Work:)
- [ ] Citation:341.18-23
- [ ] Original Language:[Ancient Greek](https://caesarea-maritima.org/search.html?fq=;fq-Original%20Language:grc)
- [ ] Place Composed:[Cyzicus](https://caesarea-maritima.org/search.html?fq=;fq-Place%20Composed:https://pleiades.stoa.org/places/511218)

**Comment by davidamichelson** [comment]
Need to discuss with Winona in person

**Comment by davidamichelson** [comment]
@wsalesky So this is technically perhaps a flaw in the design, but it seems to work (because of the strings and paths involved). Is it worth changing or can we just leave it?

**Comment by davidamichelson** [comment]
Actually, change of thought, we probably do need to change this because once one is in the whole app facet, then the banner is different and one can't get back easily to the testimonia browse.

Also, this https://caesarea-maritima.org/search.html claims it is Testimonia search but it is not the same as this: https://caesarea-maritima.org/testimonia/search.html

Can we make this change please?

**Comment by wsalesky** [comment]
Note to self: remove whole app search, should only be able to search within the publications.
