### ISSUE TITLE
Need a Logo for the Browser Tab

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#29]

**Comment by davidamichelson** [comment]
https://www.ebay.com/itm/Ancient-JUDAEA-Caesarea-Maritima-Hadrian-117-138-AD-E-Judea-City-Coin-/372787514121

**Comment by wlpotter** [comment]
@davidamichelson Here is a link to a more academic source for that coin: https://rpc.ashmus.ox.ac.uk/coins/3/3933 

Unfortunately, it doesn't appear they have an open-access image. And I haven't come across a line-drawing of it yet.

**Comment by davidamichelson** [comment]
Okay, we can wait and ask Joe Rife about this

**Comment by davidamichelson** [comment]
At the bottom of the Oxford page there is an image that could easily be converted to a line drawing: https://rpc.ashmus.ox.ac.uk/rev/62187

**Comment by wlpotter** [comment]
Would we be within copyright restrictions if we made a line drawing ourselves?

**Comment by davidamichelson** [comment]
There would be no copyright issues in making our own, but lets sit on this
until we can meet with Joe.

**Comment by davidamichelson** [comment]
@wsalesky We are ready to request your artistic skills please? What is the standard resolution for a favicon?(we tried looking here: https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/)

We would like to request a suite of icons for use in the browser tab and elsewhere.

We need just one icon that is shared by all modules.

Our preferred options are a simplified version of a coin? Could you render either one of these into a simple icon?

https://rpc.ashmus.ox.ac.uk/rev/26217/high (We like the Eagle and the Circle with tower in it, we would not need to keep the lettering)

or 

https://rpc.ashmus.ox.ac.uk/rev/22734/high (Here we like the lettering and the laurel wreath, the lettering is 
COL
PR FL
AVG F C
CAES ME
TR P S

These letters are the abbreviation for the long form name of Caesarea Maritima)

Do you think you could make a logo that is like either of these? We know you have super powers :)

**Comment by davidamichelson** [comment]
Adding the source pages as reference:
https://rpc.ashmus.ox.ac.uk/coin/22734
https://rpc.ashmus.ox.ac.uk/coins/9/2120

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter How does something like this look? I'm happy to make changes. 
![cs-logo](https://user-images.githubusercontent.com/1168206/83429435-0ccef100-a402-11ea-82ae-f55bf8ec11d8.png)

**Comment by davidamichelson** [comment]
@wsalesky We love this. Could you try the following changes please?

1. We think you can cut the tail of the eagle out and just have the wings and head. This would then allow you to lower the inner circle and make the inner circle larger because we need to augment it.
2. Could you add a few (just a few, 2 or 3) feathertips in the wings like in the original coin image? (Result might be similar but less pronounced to this: https://www.pngfuel.com/free-png/rweke)
3. Lastly the point of these changes would be to have room for the head with crown in the middle of the inner circle. The image we gave you to work with was too rough. For the inner circle this is an better image of the same coin: https://rpc.ashmus.ox.ac.uk/rev/22768/high The image is a "turreted tyche bust" or a profile female face with the city walls as her crown. (History lesson, she is the spirit of the city, so gets to wear its walls on her head :) If you want inspiration you can see better examples from other coins here: https://www.google.com/search?q=turreted+Tyche -- this is a nice one: https://www.worthpoint.com/worthopedia/phoenicia-arados-turreted-tyche-485784303  Just to be clear this bust with turrets is going to be very small and stylized, so just try to fit a head with a blocky crown please :)

**Comment by wsalesky** [comment]
![cs-logo2](https://user-images.githubusercontent.com/1168206/84049178-1e704580-a97a-11ea-8900-654b97f30b93.png)


How does this look?

**Comment by davidamichelson** [comment]
I love it, can you please send it to us in red and in a 32X32 pixel version
or what ever the sizes are that we would actually see in a browser tab and
elsewhere?

**Comment by davidamichelson** [comment]
And I do like the beak on this last image, can you hook in down even more
than 90 degrees?

**Comment by wsalesky** [comment]
What kind of red are we talking about? Flame red? Crimson? The left side of the image is warm reds, the right is cool reds... what do you think? 

<img width="357" alt="Screen Shot 2020-06-08 at 11 43 43 AM" src="https://user-images.githubusercontent.com/1168206/84051568-5d53ca80-a97d-11ea-90a5-7d43b2582f3b.png">

**Comment by wsalesky** [comment]
How about this red?

![cs-logo2](https://user-images.githubusercontent.com/1168206/84060033-85e1c180-a989-11ea-9ad7-6e3243ce7220.png)

**Comment by davidamichelson** [comment]
Great, looks good! Thanks, how does the image scale down?

**Comment by davidamichelson** [comment]
I figured out how to downsize it. I think it works, let's see what our collaborators think

**Comment by wsalesky** [comment]
Some other size options: 

![cs-logo-medium](https://user-images.githubusercontent.com/1168206/84071387-9ac75080-a99b-11ea-90bd-64c4ce906ff5.png)
![cs-logo-small](https://user-images.githubusercontent.com/1168206/84071388-9b5fe700-a99b-11ea-9a35-1d7b5b962d48.png)
![cs-logo-small2](https://user-images.githubusercontent.com/1168206/84071390-9b5fe700-a99b-11ea-9d68-dd8142e4b201.png)
![cs-logo2](https://user-images.githubusercontent.com/1168206/84071391-9b5fe700-a99b-11ea-87f6-a482df8c90e7.png)

**Comment by davidamichelson** [comment]
Great!

**Comment by wsalesky** [comment]
Added
