### ISSUE TITLE
Suppress all mentions of URN in the HTML

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#290]
Example: https://caesarea-maritima.org/testimonia/97

Alas this technology is too unstable.

There are two places for now where these occur on a testimonia page: underneath the edition and translation and in the about box.

These are generated from the TEI here:

- [ ] body/ab/idno type="CTS-URN"
- [ ] textClass/classCode/idno type="CTS-URN"

Please suppress both of these in the HTML and in the About box simply remove all mention of URN.

**Comment by wsalesky** [comment]
@davidamichelson do you want the "Browse source text." links suppressed also?

**Comment by davidamichelson** [comment]
No, leave that but we will delete the broken links from the data.

**Comment by wlpotter** [comment]
Note to self, here is the data issue for the "Browse source text" data: https://github.com/srophe/caesarea-data/issues/115

**Comment by wlpotter** [comment]
Fixed the broken links in data; URNs are suppressed in the HTML.
