### ISSUE TITLE
Rendering tei:lb in HTML

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#291]
@wsalesky we have added tei:lb elements in testimonia data (in `//text/body/ab[@type="translation" or @type="edition"]`). Could you render these tei:lb elements as a new line in the HTML?

Data is updated; as an example, see https://caesarea-maritima.org/testimonia/306.

For example, current:

>[i.e.] Judaea:Straton’s 

should be:

>[i.e.] Judaea:
>Straton’s

**Comment by wsalesky** [comment]
done
