### ISSUE TITLE
Reindex Testimonia Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#322]
The browse is broken. 

From this link: https://caesarea-maritima.org/testimonia/browse.html?lang=&alpha-filter=M (which shows M)

If one clicks on Marino Sanudo the Elder (15) on the left hand menu, one ends up at
 
https://caesarea-maritima.org/testimonia/browse.html?facet-author=Marino%20Sanudo%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20the%20Elder&lang=&alpha-filter=M

Which is empty.

<img width="1537" alt="Screen Shot 2022-09-14 at 11 48 03 AM" src="https://user-images.githubusercontent.com/3083773/190214752-e721fc74-e2c7-4faf-8684-e335af4bdf90.png">

<img width="1634" alt="Screen Shot 2022-09-14 at 11 48 13 AM" src="https://user-images.githubusercontent.com/3083773/190214779-8622d2c0-5455-4051-9cf9-5c0e14629ec6.png">

**Comment by davidamichelson** [comment]
Note, bill this to the new PO we will create.

**Comment by wsalesky** [comment]
This works, there is still something funky happening with the facets. I am opening a new issue for that.
