### ISSUE TITLE
Whitespace around <placeName>

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#323]
All testimonia records have 

body/ab that contains TEI:placeName with textnode.

These TEI:placeNames need whitespace around them.

See example here https://caesarea-maritima.org/testimonia/283

<img width="1867" alt="Whitespace Error" src="https://user-images.githubusercontent.com/3083773/190215930-bbd19be5-0dba-4ce4-bb8d-e9d6d01a7d8a.png">

**Comment by davidamichelson** [comment]
Note, bill this to the new PO we will create.

**Comment by wsalesky** [comment]
This is a data issue, not a code issue. Looks like the data on github has been updated to fix it. I will load the new data on the server.
