### ISSUE TITLE
Restore Banner Images

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#324]
Please restore the Banner images from this commit:

https://github.com/srophe/caesarea/commit/191d7fca1a9a40cacd811f207a18841a379dfbd2

Just to clarify, we want the images that this commit pushed, the aquaduct color photo and the black and white map (somehow this commit got reverted).

**Comment by davidamichelson** [comment]
@wsalesky if you could push this one Friday (tomorrow) please that would be helpful. Thanks!

**Comment by davidamichelson** [comment]
@wsalesky Actually on the main landing page: https://caesarea-maritima.org/index.html, we still need the black and white image (Caesarea Restored 1888)

**Comment by wsalesky** [comment]
@davidamichelson Did you do a hard refresh? I see it on the home page.

**Comment by davidamichelson** [comment]
Thanks, I see it now. Can you crop it differently please? On my version there is a lot of whitespace. See picture.
![Screen Shot 2022-09-23 at 8 59 50 AM](https://user-images.githubusercontent.com/3083773/191978104-a3b41ea9-c9e4-4351-934b-0609cc2afc57.png)

**Comment by wsalesky** [comment]
What browser?

**Comment by wsalesky** [comment]
@davidamichelson Is this better?

**Comment by davidamichelson** [comment]
Yes, thanks!
