### ISSUE TITLE
Whitespace in Bibligraphy citation

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#326]
There is missing whitespace in how the bibliography is pulling citations from the Zotero API. See examples from https://caesarea-maritima.org/testimonia/280

I am not sure what the XML underneath looks like because this is not in the record, it is being pulled from the API (right?).

<img width="918" alt="Screen Shot 2022-09-14 at 12 05 22 PM" src="https://user-images.githubusercontent.com/3083773/190218312-d766d44d-8063-4f0a-a29d-6b407720ac58.png">

**Comment by wsalesky** [comment]
Fixed by: https://github.com/srophe/caesarea/pull/334
