### ISSUE TITLE
Some elements in Biblography citation are getting repeated.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#327]
I am not sure if this is in the Zotero record or in the pull of the data from the Zotero API.

See this example where titles are repeated: https://caesarea-maritima.org/testimonia/280

<img width="911" alt="Screen Shot 2022-09-14 at 12 07 51 PM" src="https://user-images.githubusercontent.com/3083773/190218744-c4cc1d85-8b6c-4255-9178-5ca829446a50.png">

Records with more than one title in the same citation also have both the chapter and book title repeat. See https://caesarea-maritima.org/testimonia/202
<img width="872" alt="Screen Shot 2022-09-14 at 12 10 35 PM" src="https://user-images.githubusercontent.com/3083773/190219023-6c6e0f82-5bb0-4f05-b89f-4b7fed54d6a0.png">

**Comment by davidamichelson** [comment]
@wsalesky Will and I looked into this further. This issue seems to be created by the Zotero API or wherever you are getting the pre-formatted citation from. Note that the "Preferred citation" form here looks okay: https://caesarea-maritima.org/bibl/H3E7SNZV

**Comment by wsalesky** [comment]
fixed with https://github.com/srophe/caesarea/pull/334
