### ISSUE TITLE
abbreviated record view on browse by map (Testimonia)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#329]
On the map browse, the abbreviated version of the record (found when clicking on a pin) could be simplified please.

Currently it seems to have 

```
[Epiphanius, 69.6.1-5Caesarea Maritima: A Collection of Testimonia](https://caesarea-maritima.org/testimonia/252)
Location: [Salamis/Konstantia](https://pleiades.stoa.org/places/707617)
Relationship: Place of Origin
```
Let's simplify this as follows:
```
[Epiphanius, Medicine Cabinet, or Against Heresies 69.6.1-5](https://caesarea-maritima.org/testimonia/252)
Composed in Salamis/Konstantia
```

Delete: Caesarea Maritima: A Collection of Testimonia (titleStmt/title level=m)
Add Title of Testimonia: Medicine Cabinet, or Against Heresies 69.6.1-5 (titleStmt/title level=a including all child nodes)
Reformat Place (using body/desc type="abstract"/origPlace) so that it is shorter and has no live URLS

If when you get into the code there are other types of place than origPlace, please let me know. It looks like we are looking up the Pleiades headword for this. We could just use the contents of our own textnode, I think? @wlpotter What do you think?

**Comment by davidamichelson** [comment]
<img width="1241" alt="Screen Shot 2022-09-14 at 1 00 57 PM" src="https://user-images.githubusercontent.com/3083773/190230290-6384ff23-7ce1-44e2-bbd4-91c961c0230a.png">

**Comment by davidamichelson** [comment]
@wlpotter Do we have any other types of place besides OrigPlace in the abstracts of Testimonia?

**Comment by wlpotter** [comment]
No, the only place types we tag in the abstract (`/TEI/text/body/desc[@type="abstract]`), which is based on the `/TEI/teiHeader/profileDesc/creation`, is the tei:origPlace
