### ISSUE TITLE
Replace "How to Cite This Entry" in Bibl Module with "About this Online Entry" similar to Biblia Arabica

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#33]
For the HTML view of all Bibl Records, please remove the whole "How to Cite This Entry" section. (It is too confusing)

Instead have each entry have an "About this Online Entry" box  similar to Biblia Arabica see https://biblia-arabica.com/bibl/L7VZ2XVC

Please have the following change from Biblia Arabica, call this "About this Online Bibliography".

How is this populated? Is the "Editorial Responsibility" section hard coded?

Like the Biblia Arabica site, make this always expanded (not collapsed as default).

**Comment by davidamichelson** [comment]
Please port this feature to to Syriaca.org and main Srophé App code bases

**Comment by wsalesky** [comment]
@davidamichelson This is generated here: https://github.com/srophe/caesarea/blob/master/resources/xsl/tei2html.xsl#L150

and
https://github.com/srophe/caesarea/blob/master/resources/xsl/citation.xsl#L208

There are some control fields that will need to be added to all of our records imported from Zotero: 
https://github.com/srophe/zotero2bibl/blob/master/zotero-config.xml#L12

Let me know what they should be and I will rerun the Zotero import once I get the citation info sorted out.

**Comment by wsalesky** [comment]
@wsalesky Close after updating config.xml

**Comment by davidamichelson** [comment]
We will add more information and link to editors.xml

**Comment by wlpotter** [comment]
@wsalesky  @davidamichelson Here is the information for the control fields in https://github.com/srophe/zotero2bibl/blob/master/zotero-config.xml#L12

```
<sponsor>Vanderbilt University</sponsor>
        <principal>Joseph Rife</principal>
        <editor role="general" ref="http://caesarea-maritima.org/documentation/editors.xml#jrife">Joseph Rife</editor>
        <editor role="general" ref="http://caesarea-maritima.org/documentation/editors.xml#packerman-lieberman">Phillip
        Ackerman-Lieberman</editor>
        <editor role="technical" ref="http://caesarea-maritima.org/documentation/editors.xml#dmichelson">David A.
        Michelson</editor>
        <editor role="technical" ref="http://caesarea-maritima.org/documentation/editors.xml#wpotter">William L. Potter</editor>
        <editor role="creator" ref="http://caesarea-maritima.org/documentation/editors.xml#jrife">Joseph Rife</editor>
```
I don't believe we would need additional respStmts.

For the availability we are using a CC 4.0 license:
```
<availability>
          <licence target="http://creativecommons.org/licenses/by/4.0/">
            <p>Distributed under a Creative Commons Attribution 4.0 Unported License.</p>
          </licence>
        </availability>
```

**Comment by davidamichelson** [comment]
Note the script that converts the Zotero data would also add a creator based on the id of the person who entered the Zotero data.

**Comment by wsalesky** [comment]
Done.
