### ISSUE TITLE
Translation text missing when new `//anchor/@corresp` format is used

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#335]
@wsalesky I am updating the tei:anchor elements' `@corresp` attributes, which I believe are used to create the parallel columns of edition and translation text. (the data issue for this change is https://github.com/srophe/caesarea-data/issues/119)

Currently the `//anchor/@corresp` attribute is of the form `corresp="testimonia-306.en.1"`, but it will be updated to look like `corresp="#testimonia-306.en.1"`, with an initial "#".

I've tested the data update with https://caesarea-maritima.org/testimonia/10 and it looks like it breaks the display: the English translation, which is there in https://caesarea-maritima.org/testimonia/10.tei (`///TEI/text/body/ab[@type="translation"]`) is missing from the HTML.

The tei:anchor elements are:
```
<anchor xml:id="testimonia-10.grc.1" corresp="#testimonia-10.en.1"/>
```
and
```
<anchor xml:id="testimonia-10.en.1" corresp="#testimonia-10.grc.1"/>
```

![Screenshot from 2022-09-16 11-59-11](https://user-images.githubusercontent.com/44096602/190690954-8712719a-b992-453e-9a43-48b116c4f1f5.png)

For reference, it should look more like https://caesarea-maritima.org/testimonia/11 , with the two parallel columns. 

If I make the data updates on a separate branch but leave https://caesarea-maritima.org/testimonia/10 with the new format for you to test, could you let me know when the App is ready to handle the new `@corresp` format?

**Comment by wsalesky** [comment]
@wlpotter Done! you can go ahead and update the data.

**Comment by wsalesky** [comment]
Close when the data is updated

**Comment by wlpotter** [comment]
Okay, data is fixed. I was worried it would have crashed the webhooks, but it looks to be working!
