### ISSUE TITLE
Calling Preferred Citation from Zotero API

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#34]
PLEASE READ BELOW AS THIS ISSUE HAS CHANGED

Not sure how to handle this since I know sometimes when we change formatting it breaks it somewhere else.

See:

Avraham Biran and Joseph Aviram, "Anastasius I and the Restoration of Caesarea Maritima’s Harbor: The Numismatic Evidence." , Jerusalem: Israel Exploration Society, 1993. 

should read:

Avraham Biran and Joseph Aviram, "Anastasius I and the Restoration of Caesarea Maritima’s Harbor: The Numismatic Evidence," Jerusalem: Israel Exploration Society, 1993. 

Original:
Evidence." , Jerusalem:
Changed:
Evidence," Jerusalem:

**Comment by davidamichelson** [comment]
Change is move comma, replace period, remove whitespace

But do we need to talk first about the stylesheets before we edit them? This may be related to item type?

**Comment by davidamichelson** [comment]
This is on the entry page, but also seems to be a related issue on the Browse view

**Comment by davidamichelson** [comment]
New solution to issues #34, #35, #36 

Please call two types of preformatted citation from the Zotero API: the preferred "Bibliography" and the preferred "Citation" for Chicago Style 17th Full Note from the Zotero API (see stylesheet here: https://www.zotero.org/styles?q=id%3Achicago-fullnote-bibliography).

We will use this in the following way:

On the Browse page and Search Results lists use the "Bibliography" (bib) style.

When creating a source note on an entry page (in Testimonia entry) use the "Citation" style.

On the Bibl entry page give both.

Note to future work: for odd data it may be possible to create a work around with HTML in Note in Zotero for PO volumes for example.

**Comment by wsalesky** [comment]
Updated. Needs review. @davidamichelson @wlpotter

**Comment by wsalesky** [comment]
Fixed.
