### ISSUE TITLE
tei:title and tei:foreign elements should be rendered in italics

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#342]
Split off from https://github.com/srophe/caesarea-data/issues/120. We'd like to have tei:title elements inside the tei:desc elements display in italics.

Full path: `/TEI/text/body/desc[@type="context"]/title`.

Example record: https://caesarea-maritima.org/testimonia/234

The phrase "Secrets for Those Faithful to the Cross (Secreta fidelium Crucis)" in the initial "Context" paragraph should render in italics.

**Comment by wlpotter** [comment]
Making this a bit more general. The following cases should be rendered in italics:

- `/TEI/text/body/desc[@type="context"]/title`
- `/TEI/text/body/desc[@type="context"]/foreign`
- `/TEI/text/body/ab/title`
- `/TEI/text/body/ab/foreign`
- `/TEI/text/body/ab/note/title`
- `/TEI/text/body/ab/note/foreign`

**Comment by wsalesky** [comment]
fixed
