### ISSUE TITLE
Footnote Numbers not Displaying on the Testimonia Record Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#348]
@wsalesky the footnotes numbers are not appearing on the record page for the text node when an element that has `@source`. For example see https://caesarea-maritima.org/testimonia/370

On this page there should be a footnote 1 after the word "debueris." and 2 after " questioners." coming from
```
<ab type="edition" xml:lang="la" xml:id="quote370-1" source="#bib370-1">
and
<ab type="translation" xml:lang="en" xml:id="quote370-2" source="#bib370-2">
```

These footnote numbers do appear in the bibliography at the bottom of the page, which is good, but they don't appear in the textboxes for Text and Translation.

Can you make them appear again please?

**Comment by wsalesky** [comment]
I can add the footnotes, but they will appear after the notes, see the TEI: 
https://github.com/srophe/caesarea-data/blob/master/data/testimonia/tei/370.xml#L278-L294

It looks a little awkward.

**Comment by davidamichelson** [comment]
Okay, sounds like we should introduce a child TEI:ab inside the first
TEI:ab and add the @source to that but before the note?

**Comment by davidamichelson** [comment]
Actually, could you put the note number on the words "Text" and "Edition"?

**Comment by wsalesky** [comment]
Done

**Comment by davidamichelson** [comment]
Thanks Winona, I'm reopening just so Will and I can decide about how it looks.

**Comment by wlpotter** [comment]
@wsalesky there is now a `//body/ab/ab[@type="source]` in each of the excerpts (edition and translation). I have made sure these are placed directly after the end of the text, and before the note elements. The ab element has a `@source` attribute that points to one of the bibl xml:ids, so this should allow you to generate the footnote numbers in the correct place. Let me know if you need further data edits on this issue

**Comment by wsalesky** [comment]
Done.
