### ISSUE TITLE
More than three author names in Bibl Browse View

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#35]
When there are more than three authors, the list is abbreviated but missing:

See: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/browse.html?start=1&perpage=632

The Young (Post-Pliocene) Geological History of the Caesarea Structure
D Neev, E Schachnai and J.K. Hall,, "The Young (Post-Pliocene) Geological History of the Caesarea Structure."Israel Journal of Earth Sciences vol. 27 (1978)
URI: https://caesarea-maritima.org/bibl/62MTHID7

Notice: J.K. Hall,, "The Young

**Comment by davidamichelson** [comment]
I actually only have one example of this, so not sure if the number of authors is the cause or what.

**Comment by wsalesky** [comment]
Possibly solved with: https://github.com/srophe/caesarea/commit/4a3924df2de1cdfc5c0ce4f51851500ad878ae49
