### ISSUE TITLE
Display for original language vs testimonia language

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#355]
Cf. https://github.com/srophe/caesarea-data/issues/132. Testimonia records will have two `///TEI/teiHeader/profileDesc/langUsage/language` elements, distinguished by the `@ana` attribute.

Example record: https://caesarea-maritima.org/testimonia/405

Each of the `language` elements should be treated separately:

1. `language[@ana="#caesarea-language-of-testimonia"]` should have the label "Language of Testimonium", and should appear first (it will be listed first in document order)
2. `language[@ana="#caesarea-language-of-original"]` should have the label "Language of Original", and should appear below the other language, and should be indented.

@davidamichelson please feel free to revise or correct any of the above.

**Comment by wsalesky** [comment]
Fixed

**Comment by wsalesky** [comment]
Opps, maybe this was for the next meeting, reopening for discussion.

**Comment by wlpotter** [comment]
Yes, sorry should have made that clear...Though it will be good to have a visual to look at!

**Comment by davidamichelson** [comment]
Please add colons after:

Language of Testimonium:
Language of Original:

**Comment by wsalesky** [comment]
fixed
