### ISSUE TITLE
Bug in facets

### ISSUE THREAD

**Issue by wsalesky** [srophe/caesarea#359]
Facets frequently appear where they should not, go to browse, select any letter and examine the author facets, several of them should not be in the result set at all.

**Comment by davidamichelson** [comment]
As a temporary fix, please hide the facet sidebar until Thursday, October 27.

**Comment by davidamichelson** [comment]
Okay, should we move to the development branch of Exist for facets?

**Comment by wsalesky** [comment]
@davidamichelson I will test it and see if it is an improvement.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter I have added the facets back in, they seem to be behaving better this time around. Let me know if you find any bugs.
