### ISSUE TITLE
Missing Punctuation and Whitespace on Bibl Browse View

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#36]
Same caveats apply about editing the styles here. Should we talk on Monday first?

There is a missing period (at the end) and a missing white space (after title, before Journal name). See http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/browse.html?start=1&perpage=632 

Current:
Warren J Moulton, "Gleaning in Archaeology and Epigraphy: A Caesarean Inscription."AASOR vol. 1 (1919-1920)

Fixed:
Warren J Moulton, "Gleaning in Archaeology and Epigraphy: A Caesarean Inscription." AASOR vol. 1 (1919-1920).

**Comment by wsalesky** [comment]
@davidamichelson How does it look now? I am using the formatted citation (tei:bibl/@type='formatted')  that is in the record, if it exists.
