### ISSUE TITLE
Right align Syriac, Arabic, and Hebrew language tags

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#363]
https://caesarea-maritima.org/testimonia/393
https://caesarea-maritima.org/testimonia/405

Please expand the stylesheet to right align textnodes which have xml:lang= syr, ar, he, tmr, jpa

**Comment by davidamichelson** [comment]
Hmm, any thoughts on a solution?

**Comment by davidamichelson** [comment]
Also did we make an issue about how the placeName element is causing the font size to change? See https://caesarea-maritima.org/testimonia/405

**Comment by wsalesky** [comment]
Yes, the notes need a xml:lang="eng" element.  I will experiment on the size change issue.

**Comment by davidamichelson** [comment]
Okay we can fix the notes.

**Comment by wsalesky** [comment]
@davidamichelson close if complete
