### ISSUE TITLE
Facets for Bibl Browse View

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#37]
We will want facets and maybe a timeline view. Let's discuss first.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter We forgot to discuss this. Want to give me a few, just so the facets are not empty?

**Comment by davidamichelson** [comment]
Facet by:
Item Type  ->("Zotero Category") -- need to put item type into TEI
Language
Publication Date -> Use the publication date ranges also used by Biblia Arabica
Historical Testimonia -> This will be added to the Zotero record and the TEI

Sort by:
Author/Creator Last Name Alphabetical
Title Alphabetical
Date Newest to Oldest
Date Oldest to Newest

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter The publication date facet is made of predefined ranges, so I will need to know where to start, and how big a range you want for each 'bucket'

**Comment by davidamichelson** [comment]
@wsalesky please use 10 year ranges for dates.

Also, we have records from before 1850 but they are not currently showing in the browse: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/HMUGB5SQ 

Thanks!

**Comment by wlpotter** [comment]
Our earliest record is 1745, so 1740 would be the earliest starting point for buckets.

Our latest record is 2019.

**Comment by wsalesky** [comment]
If we do this by decade, that will be a lot of facets. What about experimenting with a data slider instead?

**Comment by davidamichelson** [comment]
Sure that sounds more elegant and is exactly why we need you so much!

**Comment by davidamichelson** [comment]
@wsalesky please implement a slider

**Comment by wsalesky** [comment]
Date slider added.
