### ISSUE TITLE
Syriac in tei:placeName elements in the edition should have the same font size and style

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#371]
@wsalesky Splitting this off from [this comment](https://github.com/srophe/caesarea/issues/363#issuecomment-1287099689) in #363. I think this can wait until after the presentation on Tuesday, FYI (unless it's a really quick and unobtrusive edit).

When Syriac text is tagged in a tei:placeName element in the edition tei:ab (`//body/ab[@type="edition"]/placeName`), the Syriac font is rendered in the HTML differently than the surrounding Syriac text (i.e., what isn't tagged in the placeName element).

Example: https://caesarea-maritima.org/testimonia/405 (the last line of text and the three leftmost words on the line above it are a larger font size, and maybe bolded, compared to the rest. These are all tagged in a tei:placeName element)

![Screenshot from 2022-10-24 17-38-17](https://user-images.githubusercontent.com/44096602/197643111-28889548-da9c-4925-8d1e-5334dc45e353.png)

**Comment by wsalesky** [comment]
@wlpotter is this still an issue?

**Comment by wlpotter** [comment]
No, this looks to be fixed!
