### ISSUE TITLE
Display "Historical Era(s) Mentioned:" in About this Text

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#373]
This information is found in `profileDesc/textClass/catRef @scheme="#CM-NEAEH"`

**Comment by wlpotter** [comment]
@wsalesky here's a bit more info on this issue.

Label will be "Historical Era(s) Mentioned" and will show up in the "About this Text" box under Historical Era Composed. It should be the same processing as creates the "Historical Era Composed" piece field but using the below xpath to get the data:

The data is in `//profileDesc/textClass/catRef[@scheme="#CM-NEAEH"]/@target`. They will be space-separated uri fragments, e.g. `<catRef scheme="#CM-NEAEH" target="#byzantine"/>`. These values correspond to the `catId` elements in the [Historical Era Taxonomy](https://github.com/srophe/caesarea/blob/master/documentation/caesarea-maritima-historical-era-taxonomy.xml).

They can be parsed and displayed in the same way as the `//origDate/@period` attribute is, with the label and faceted browse link.

**Comment by wsalesky** [comment]
Done

**Comment by davidamichelson** [comment]
Thanks!
