### ISSUE TITLE
Format the "Historical Era Composed" dates when there are multiples

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#374]
See testimonia 1, 43, 44, 220, 413, 414

For example https://caesarea-maritima.org/testimonia/220 
![Screen Shot 2022-11-11 at 1 51 24 PM](https://user-images.githubusercontent.com/3083773/201421400-27ad2187-ba4d-4813-9158-9ad12a37b1b6.png)

Please put each of these date periods on a new line so they are all left justified and look tidy like this

Nabatean Kingdom, 167 BCE-106 CE 
Early Roman Period, 36 BCE-132 CE
Herodian Period, 36 BCE-70 CE 
Middle Nabatean Period, 24 BCE-50 CE

**Comment by wsalesky** [comment]
Done!
