### ISSUE TITLE
Srophe Zotero to TEI bibliography

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#375]
@wsalesky is it the case that the main Srophé app has more features for this page: 
https://caesarea-maritima.org/zotero2bibl/index.html

Could we upgrade the CM to have the most recent version?

**Comment by wsalesky** [comment]
Check to make sure this is the most up to date version of zoter2bibl

**Comment by wsalesky** [comment]
@davidamichelson They are the same. What features are you missing?

**Comment by wsalesky** [comment]
I did find and fix a bug. If there are any specific features that are missing, let me know, the code looks the same expect for a few Caesarea specific additions.

**Comment by davidamichelson** [comment]
Loading bar looks great!
