### ISSUE TITLE
words wrapped with TEI:foriegn are not displaying with italics

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#376]
I found that some words that I marked as "foreign" using drop-down menu following option+E on the data-entry template are not showing up as italicized on the website. E.g. 45, 46, 216, 394. Is it possible that the program is not searching for foreign words to automatically italicize outside of certain data-emtry fields? I have tried to italicize words as foreign (though it also the case with titles, I have found) in the following fields: Context; text; translation; textual note(s); translation note(s); discussion note(s)--but again they dont all show up on the website as italicized.

**Comment by davidamichelson** [comment]
@wsalesky words wrapped with TEI:foriegn are not displaying with italics. Could you check on this please?

**Comment by wlpotter** [comment]
FYI this is related to #342

**Comment by davidamichelson** [comment]
See https://caesarea-maritima.org/testimonia/45

**Comment by wsalesky** [comment]
fixed
