### ISSUE TITLE
Bibliography module records showing up in Testimonia browse

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#38]
@wsalesky The bibliography module records are appearing in the Testimonia browse: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/browse.html

We would like to keep the two sub-module browse pages separate. 

FWIW, the testimonia are _not_ appearing in the bibl browse (http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/browse.html)

**Comment by wsalesky** [comment]
Fix bug.
