### ISSUE TITLE
Update style of "Browse Source Text" link

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea#381]
We dont need this here anymore, only a place to link over to an online source when that is useful

**Comment by wlpotter** [comment]
Data issue now in https://github.com/srophe/caesarea-data/issues/164

**Comment by wlpotter** [comment]
Oh sorry, @wsalesky I forgot that the other part of this is to update the format of these "Browse Source Text" links. 

From @davidamichelson 's comment [above](https://github.com/srophe/caesarea/issues/381#issuecomment-1334457799)
> Also, while you are at it can you change the styling on "Browse source text". Please set the font size to be smaller, the same as "Textual Note" in https://caesarea-maritima.org/testimonia/130

**Comment by wsalesky** [comment]
Fixed styles.
