### ISSUE TITLE
Display the related subjects

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#388]
Example record: https://caesarea-maritima.org/testimonia/381

Data is in `/TEI/text/body/listRef`. 

This data can display in the about this text box, after the "Historical Era(s) Mentioned".

- Each `listRef` will have a tei:desc element that will serve as the label for the list, and can be formatted like the other labels in the "about this text" box (e..g., )
- The text node of each child tei:ref element should appear on its own line, indented like the data under the "Historical Era(s) Composed" and "Historical Era(s) Mentioned" fields.
- The `@target` attribute, which is optional, can for now be used to create a hyperlink. We may use this to create additional browse facets, but that will be a separate issue.

There should be four `listRef` elements:

- related-texts
- geography
- prosopography
- themes

If there is no data in a category, i.e. there is no child tei:ref element, the category should not be displayed

**Comment by wlpotter** [comment]
@wsalesky This should be ready to go, and I've updated the data for the above linked example record. Let me know if I can clarify any of this. Thanks much!

**Comment by wsalesky** [comment]
@wlpotter added

**Comment by wsalesky** [comment]
Fixed bug in ptr and ref display.
