### ISSUE TITLE
Updating Works cited on Testimonia records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#39]
@wsalesky we would like to use a similar function to the one you wrote for [this Beth Qatraye issue] (https://github.com/srophe/bethqatraye-data/issues/50) to update the works cited information for Testimonia records based on the  `/TEI/text/body/listBibl/bibl/ptr/@target` value, which is a pointer to the bibl module. We would want to return the title and creator information and update the testimonia record's `/TEI/text/body/listBibl/bibl` with that information.

**Comment by wsalesky** [comment]
@wlpotter You can review the data from running the script here: 
https://github.com/srophe/caesarea-data/tree/issue39

Merge into master if it looks okay. Otherwise post issues and I will update the script.

**Comment by wlpotter** [comment]
Looks great! I merged into master. (https://github.com/srophe/caesarea-data/pull/10).
