### ISSUE TITLE
Faceted Browse links in About this Text Box not working

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#393]
The links in the "About this Text Box", which should point to a faceted browse, do not appear to be working.

Example record: https://caesarea-maritima.org/testimonia/307

- Author: https://caesarea-maritima.org/search.html?facet-author=Adomn%C3%A1n
    - facet does not appear to be working
- Title: https://caesarea-maritima.org/search.html?facet-work=Holy%20Places
    - facet does not appear to be working
- Language of Testimonium: https://caesarea-maritima.org/search.html?facet-originalLanguage=
    - link not being constructed. I believe Xpath is needed?
    - Xpath for this value: `/TEI/teiHeader/profileDesc/langUsage/language[@ana="#caesarea-language-of-testimonia"]`, `./@ident` has the ISO language code, e.g. "la"; `./text()` has the human readable label, e.g. "Latin"
- Language of Original: https://caesarea-maritima.org/search.html?facet-originalLanguage=
     - link not being constructed. I believe Xpath is needed?
    - Xpath for this value: `/TEI/teiHeader/profileDesc/langUsage/language[@ana="#caesarea-language-of-original"]`, `./@ident` has the ISO language code, e.g. "la"; `./text()` has the human readable label, e.g. "Latin"
- Place Composed: https://caesarea-maritima.org/search.html?facet-placeComposed=
    - link not being constructed
    - Xpath: `/TEI/teiHeader/profileDesc/creation/origPlace` (maybe previously this was using a Pleiades link in the `/@ref`?)
- Date Composed: https://caesarea-maritima.org/browse.html?view=timeline&slideID=https://caesarea-maritima.org/testimonia/307/tei
    - Not sure what data is needed here?
- Historical Era Composed: https://caesarea-maritima.org/search.html?facet-eraComposed=Early%20Islamic%20Period%2C%20638-1099%20CE
    - facet does not appear to be working
- Historical Era Mentioned: https://caesarea-maritima.org/search.html?facet-eraMentioned=Iron%20Age%20IB%2C%201149-999%20BCE
    - facet does not appear to be working

**Comment by wlpotter** [comment]
#289 seems to be related to this issue?

**Comment by wsalesky** [comment]
@wlpotter fixed, except place composed is coming up empty. Will have to investigate.

**Comment by wlpotter** [comment]
Hmm I think that one's a problem with that record? Other records, e.g. https://caesarea-maritima.org/testimonia/300 work for the place composed. The origin place does appear in `//creation/origPlace` in record 307.

I wonder if we need to re-index? 307 is the only one composed in Iona, and is a newer addition to the dB so "Iona" might not appear in the index

----

I also noticed that the Language of Testimonium and Language of Original are using the same facet. We should probably split those out into two; in most cases they will be the same, but some records (e.g., https://caesarea-maritima.org/testimonia/405) will be different, so we will want to distinguish. We probably didn't discuss with you when we added this; I can create a separate issue for this one if that would be helpful?

It might also be worth having a separate issue for the "Date Composed" as the [Timeline browse](https://caesarea-maritima.org/testimonia/browse.html?view=timeline) doesn't appear to be working?

**Comment by wsalesky** [comment]
@wlpotter It is odd, because I have reindexed on my machine, and the data looks, fine, but Iona is not appearing in the indexes at all. We should leave this open while I investigate. 

Yes, please open new issues for the language and date composed bugs.

**Comment by wlpotter** [comment]
Split the language and date composed issues into #404 and #405, respectively. I'll leave this open for determining the issue with Iona

**Comment by wlpotter** [comment]
Split the Iona issue into #425. Everything else is working here
