### ISSUE TITLE
Draft status for individual records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#394]
We'd like to indicate to users when certain records are still in draft form. Since some have received editorial review but others have not, we'd like to be able to display this on a record-by-record basis. Is there a mechanism already in the App for this? And can we discuss what data changes will be needed to facilitate this functionality?

**Comment by wsalesky** [comment]
@wlpotter Just to confirm, the xpath for this us : TEI/teiHeader/revisionDesc/@status

**Comment by wsalesky** [comment]
@wlpotter Do you always want the record status to show, or only when @status='draft'?

**Comment by wlpotter** [comment]
Thanks for this! I'm not sure. Where does this get displayed?

I believe we want this as a way to alert users immediately if a record is in 'draft' form, so most likely just when `@status="draft"`. @davidamichelson what do you think?

**Comment by wsalesky** [comment]
Currently coded to show up only for draft status. See: https://caesarea-maritima.org/testimonia/307

**Comment by wlpotter** [comment]
Just confirming that this looks great to me!
