### ISSUE TITLE
Advanced search by Author or Place name not working

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#395]
Using the Advanced Search page does not appear to work for Author or Place name

Author search for "Josephus" yields no results (https://caesarea-maritima.org/testimonia/search.html?keyword=&title=&author=Josephus&placeName=)

Place name search for Caesarea yields no results (https://caesarea-maritima.org/testimonia/search.html?keyword=&title=&author=&placeName=Caesarea)

**Comment by wsalesky** [comment]
@wsalesky Note to self, placeName needs to include placeName and origPlace

**Comment by wsalesky** [comment]
Fixed
