### ISSUE TITLE
Remove duplicate formatted citation from bibl records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#40]
See, e.g., http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/62MTHID7

There is both the "Preferred Citation" box, which we would like to keep and a second formatted citation below the "Full Citation Information". Please remove this second formatted citation. 

See the following screenshot for reference:

![Capture](https://user-images.githubusercontent.com/44096602/77797012-5257f200-703e-11ea-8d98-c22c4738ff5c.PNG)

**Comment by wsalesky** [comment]
Fixed.
