### ISSUE TITLE
Create facet for "Language of Testimonium"

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#404]
Split off from #393. Example record: https://caesarea-maritima.org/testimonia/405

For testimonia records we now have both "Language of Original" and "Language of Testimonium". Cf. the related issue for displaying these data separately on the record page: #355 

Language of Original is working (linked to the facet: https://caesarea-maritima.org/search.html?facet-originalLanguage=), but we would like to implement a "Language of Testimonium" facet.

Data is here: `/TEI/teiHeader/profileDesc/langUsage/language[@ana="#caesarea-language-of-testimonia"]`. ISO language code is in `./@ident`; human readable label is in `./text()`.

Could we please have:
1. A browse facet in https://caesarea-maritima.org/testimonia/browse.html with the label "Language of Testimonium". It can appear below the "Original Language" facet
2. A link from the "About this Text Box" data point labeled "Language of Testimonium" to a faceted browse on that value (cf. #393)
    - Note: this would be nearly equivalent to the `facet-originalLanguage` but using the other language information.

**Comment by wsalesky** [comment]
Done
