### ISSUE TITLE
Timeline browse showing no results

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#405]
Split off from #393. The Timeline browse for testimonia records: https://caesarea-maritima.org/testimonia/browse.html?view=timeline does not appear to show any results, even when eras are selected, e.g https://caesarea-maritima.org/testimonia/browse.html?view=timeline&fq=;fq-Historical%20Era%20Composed:%23earlyHellenistic

This may need discussion as I don't remember the intended functionality?

This may be why the "Date Composed" link from the "About this Text" box is not currently working in #393 ?

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Lets talk about this at the next meeting. The version we use is no longer supported, so we should migrate, or stop using.

**Comment by davidamichelson** [comment]
Okay good to know. I am out this week, so let's check in next week.

DM

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter This one has been resolved. There are some style issues remaining, but the timeline works again.

**Comment by davidamichelson** [comment]
Great! Nice to have this working again!

Here are a few wish list items:

- [ ] The facet buttons ("Byzantine Period", "Early Islamic", etc) are in alphabetical order, but it would make more sense to have them in date order. Can we let you know the order we want them in and you list them manually?
![Screen Shot 2023-05-24 at 10 37 38 AM](https://github.com/srophe/caesarea/assets/3083773/32c382dc-7bdb-4890-b82c-5a1b11275790)

- [ ] On the timeline itself, when you click on a record then it lists its details above which is great, but you can't click through to see the record. Can we add that please? (See the Unknown, Invocation of Isis):
![Screen Shot 2023-05-24 at 10 40 29 AM](https://github.com/srophe/caesarea/assets/3083773/efc919d7-bc85-44e7-a73c-d3c1b1ce8b9e)

- [ ] The faded grey coloring of the timeline is hard to read, can we edit the color scheme at all?

- [ ] The timeline seems to hang if used too much "504 Gateway Time-out"

**Comment by davidamichelson** [comment]
For the dates and sort order, see https://github.com/srophe/caesarea/blob/master/documentation/caesarea-maritima-historical-era-taxonomy.xml

**Comment by davidamichelson** [comment]
@wsalesky Let's review this in person on the 16th.

**Comment by wsalesky** [comment]
Removed for now. https://github.com/srophe/caesarea/pull/430
