### ISSUE TITLE
Edits to About this Online Bibliography

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#421]
Was https://github.com/srophe/caesarea/issues/110

Winona, we would like to edit these sections on bibl record pages: (example from https://caesarea-maritima.org/bibl/4P84PTWA)

Copyright and License for Reuse

The full data set is released for reuse under a Creative Commons Attribution 4.0 Unported License. Individual bibliographic entries are factual data considered to be in the public domain in the United States of America and many other jurisdictions.

About this Online Bibliography

Editorial Responsibility:

    Joseph Rife, general editor, Vanderbilt University
    Joseph Rife and Phillip Ackerman-Lieberman, editors, Caesarea-Maritima.org
    Joseph Rife, entry contributor, “Anastasius I and the Restoration of Caesarea Maritima’s Harbor: The Numismatic Evidence”
    William L. Potter, entry contributor, “Anastasius I and the Restoration of Caesarea Maritima’s Harbor: The Numismatic Evidence”

Additional Credit:

    Record added to Zotero by William L. Potter

- [x] @wsalesky Can you please point us to the templates that we should edit?

thanks,
Dave

**Comment by davidamichelson** [comment]
For @wlpotter This is the mock up:
**About Caesarea Maritima: A Comprehensive Bibliography**
**How to Cite:**
Joseph L. Rife, ed., A Comprehensive Bibliography on Caesarea Maritima (Nashville, TN: Caesarea City and Port Exploration Project, 2023),[ https://caesarea-maritima.org/bibl/index.html](https://caesarea-maritima.org/bibl/index.html).
**Copyright and License for Reuse:**
The full data set is released for reuse under a Creative Commons Attribution 4.0 Unported License. Individual bibliographic entries are factual data considered to be in the public domain in the United States of America and many other jurisdictions.
**Editorial Responsibility for This Entry:**
Joseph Rife, general editor
Joseph Rife, entry contributor, https://caesarea-maritima.org/bibl/4P84PTWA
William L. Potter, entry contributor, https://caesarea-maritima.org/bibl/4P84PTWA
**Additional Credit:**
Record added to Zotero by William L. Potter

**Comment by wlpotter** [comment]
Note some changes for this were made in https://github.com/srophe/caesarea/pull/422

**Comment by wsalesky** [comment]
@davidamichelson Changes to the HTML the TEI? Both?
TEI, we would change the template as @wlpotter did in #422 
HTML Changes would go here: 
https://github.com/srophe/caesarea/blob/main/resources/xsl/tei2html.xsl#L507

and possibly here: 
https://github.com/srophe/caesarea/blob/main/resources/xsl/citation.xsl

**Comment by davidamichelson** [comment]
Hi @wlpotter @wsalesky , let's discuss this tomorrow. Thanks!

**Comment by wlpotter** [comment]
@wsalesky here is the mockup (copied from above comment, though I updated to use html headings). This will apply _only_ to the Bibl records. I'll annotate with xpaths below:

### About _Caesarea Maritima: A Comprehensive Bibliography_

#### How to Cite:

Joseph L. Rife, ed., _A Comprehensive Bibliography on Caesarea Maritima_ (Nashville, TN: Caesarea City and Port Exploration Project, 2023), [https://caesarea-maritima.org/bibl/index.html](https://caesarea-maritima.org/bibl/index.html).

#### Copyright and License for Reuse:

The full data set is released for reuse under a Creative Commons Attribution 4.0 Unported License. Individual bibliographic entries are factual data considered to be in the public domain in the United States of America and many other jurisdictions.

### Editorial Responsibility for This Entry:

Joseph Rife, general editor
Joseph Rife, entry contributor, https://caesarea-maritima.org/bibl/4P84PTWA
William L. Potter, entry contributor, https://caesarea-maritima.org/bibl/4P84PTWA

#### Additional Credit:

Record added to Zotero by William L. Potter

----
- About _Caesarea Maritima: A Comprehensive Bibliography_ = hard coded (or could use the collection title in [repo-config.xml](https://github.com/srophe/caesarea#L78)
- How to cite = hard coded
- Joseph L. Rife, ed., _A Comprehensive Bibliography on Caesarea Maritima_... = I think this is hard-coded? (it should match what's in the [bibl index](https://github.com/srophe/caesarea/blob/main/bibl/index.html#L67)
- Copyright and License for Reuse: = hard-coded
- The full data set is released for reuse under a Creative Commons... = `/TEI/teiHeader/fileDesc/publicationStmt/availability/licence/p` in the bibl record (set by zotero-config.xml).
- Editorial Responsibility for This Entry: = hard-coded
- Joseph Rife, general editor = `/TEI/teiHeader/fileDesc/titleStmt/editor[@role="general"]/text()` (set by zotero-config.xml, which we've updated to just include Joseph Rife)
- Joseph Rife, entry contributor, https://caesarea-maritima.org/bibl/4P84PTWA = `/TEI/teiHeader/fileDesc/titleStmt/editor[@role="creator"]/text()`. The change from how it already functions is that the record URI should be appended, though not sure how best to grab reliably? Either `/TEI/teiHeader/fileDesc/publicationStmt/idno` (but substring-before the "/tei") or `/TEI/text/body/biblStruct/analytic/idno[1]`
    - William L. Potter, entry contributor... is the same, i.e. process all `editor[@role="creator]` the same way
- Additional Credit = hard-coded. This functionality is already built in and shouldn't need to change
- Record added to Zotero by William L. Potter = `/TEI/teiHeader/fileDesc/titleStmt/respStmt`, using both the `resp` and `name` elements. This functionality is already built in and shouldn't need to change

**Comment by davidamichelson** [comment]
@wsalesky This is in your court now, do you need anything more from us?

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Done. Please review.

**Comment by davidamichelson** [comment]
Looks great! One change please. There are now two sections "Copyright and License for Reuse". Please delete the one that comes above: About Caesarea Maritima: A Comprehensive Bibliography. See image attached (please delete the one marked in r
![Screenshot 2023-09-18 at 1 52 08 PM](https://github.com/srophe/caesarea/assets/3083773/9a6fa8ea-daae-4af6-b99f-4404f97a2208)
ed).

**Comment by wsalesky** [comment]
Fixed
