### ISSUE TITLE
Typo:  This advanaced function searches the TEI XML records for all testimonia. 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#426]
@wsalesky Can you help us find where in the

**Comment by davidamichelson** [comment]
https://github.com/srophe/caesarea/pull/422

**Comment by wlpotter** [comment]
should be able to change in these two files: https://github.com/search?q=repo%3Asrophe%2Fcaesarea%20advanaced&type=code

**Comment by wsalesky** [comment]
@wlpotter Yes, that should do the trick.
