### ISSUE TITLE
Main Landing Page and Data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#43]
This issue refers to http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/index.html

Currently the app has a browse function that combines both modules:
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html

At present we do not need this cross-module browse function as it is confusing and to make it usable will require a good deal of work.

So please delete the following two elements on .../caesarea/index.html :

The "Read the Docs" Button and the "Browse" menu button in the banner which point to .../caesarea/browse.html (Do we also need to remove that page, could someone find it by accident?)

We do want to keep the "Search" box for now and allow cross-module search. But I think we would want the results to be sorted into two groups by module. How hard would that be to do? Don't do it before we can discuss.

**Comment by wsalesky** [comment]
Done.

**Comment by davidamichelson** [comment]
Great work! Thanks
