### ISSUE TITLE
Feature Tiles do not stretch with window

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#44]
On http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/index.html

The two Features boxes do not center or expand when the window is stretched on a 27 inch monitor. Can you get them to expand/center please?

See image. 
![Screen Shot 2020-03-30 at 12 08 30 PM](https://user-images.githubusercontent.com/3083773/77941079-342d0480-727f-11ea-856d-257c7bf2e17f.png)

**Comment by wsalesky** [comment]
@davidamichelson they should now fill the screen.

**Comment by davidamichelson** [comment]
Great work! Thank you, but now the image is too small so it repeats itself in the box. Can you fix the image to just increase its resolution to match?
![Uploading Screen Shot 2020-03-30 at 12.58.01 PM.png…]()

**Comment by davidamichelson** [comment]
<img width="2502" alt="Screen Shot 2020-03-30 at 12 58 01 PM" src="https://user-images.githubusercontent.com/3083773/77945513-63933f80-7286-11ea-991b-14cc76045c5b.png">

**Comment by davidamichelson** [comment]
perfect. Thanks!
