### ISSUE TITLE
Bibliography records OCLC URI

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#46]
@wsalesky the OCLC URI is not generating correctly on some records. See, for example, http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/S935RWI7.

The URI renders in this example as "http://www.worldcat.org/oclc/1070421280%20Abbreviation:%20RBNE". 

Compare the "Extra" field in the Zotero record: https://www.zotero.org/groups/2320447/caesarea-maritima/items/S935RWI7. 

We ended up encoding various types of information in Zotero's "Extra" field as new-line separated key: value pairs, following [this page](https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra) of Zotero's documentation. Would it be possible to parse this field to grab just the OCLC number? To my recollection, the OCLC number should be the first key: value pair in any record. 

(here is I think how the JSON export would render the field: https://gist.github.com/wlpotter/6ef9372b0f6f079be21d565cafb3effd#file-s935rwi7-json-L12)

**Comment by wsalesky** [comment]
@wlpotter Just to be clear, you do not want me to capture any of the other key:value pairs? Just the OCLC?

**Comment by wlpotter** [comment]
@wsalesky For now we just want the OCLC

**Comment by wsalesky** [comment]
Fixed, and the data has been updated as well.
