### ISSUE TITLE
Import Zotero 'related items' URIs to TEI

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#48]
We would like to use Zotero's 'related items' feature to connect multiple bibliographic record URIs in the TEI import. 

Details and discussion to follow.

**Comment by wlpotter** [comment]
@wlpotter add example Zotero records for this.

**Comment by davidamichelson** [comment]
@wlpotter Please add some examples of related records and a TEI mock up.

**Comment by wlpotter** [comment]
@wsalesky Here are examples of Zotero records which are related via the related-items feature:

1. https://www.zotero.org/groups/2320447/items/68KPMACB
is related to
2. https://www.zotero.org/groups/2320447/items/P9X8IHTU
which is related to the first record and to
3. https://www.zotero.org/groups/2320447/items/TJ39ZZJT

As an example of the API return, see the highlighted lines in [this gist](https://gist.github.com/wlpotter/48a9b2ff8a9f754c4bd9da5a1822bda6#file-api-return-68kpmacb-json-L85-L87)

----

We would like to include this related item data in the TEI XML output of the Zotero records as `te:listRelation` elements. 

See the below examples of this output, based on the above Zotero records. The path of these elements will be `/TEI/text/body/listRelation` and should look as follows:

1. https://caesarea-maritima.org/bibl/68KPMACB
```
<listRelation>
    <relation name="see-also" mutual="https://caesarea-maritima.org/bibl/68KPMACB https://caesarea-maritima.org/bibl/P9X8IHTU"/>
</listRelation>
```
2. https://caesarea-maritima.org/bibl/P9X8IHTU
```
<listRelation>
    <relation name="see-also" mutual="https://caesarea-maritima.org/bibl/P9X8IHTU https://caesarea-maritima.org/bibl/TJ39ZZJT https://caesarea-maritima.org/bibl/68KPMACB"/>
</listRelation>
```
3. https://caesarea-maritima.org/bibl/TJ39ZZJT
```
<listRelation>
    <relation name="see-also" mutual="https://caesarea-maritima.org/bibl/TJ39ZZJT https://caesarea-maritima.org/bibl/P9X8IHTU"/>
</listRelation>
```

**Comment by davidamichelson** [comment]
@wsalesky Please make this change to how we generate TEI from the Zotero. Does Nathan do anything similar? We will want this feature in other versions of the app please.

**Comment by wsalesky** [comment]
@wlpotter This change has been made. Can you take a look and close if it works as expected.

**Comment by wsalesky** [comment]
@wlpotter I found a bug in the relationships. Will fix today.

**Comment by wsalesky** [comment]
Fixed. @davidamichelson @wlpotter please review.

**Comment by davidamichelson** [comment]
Great, there is a now a related HTML issue here: https://github.com/srophe/caesarea/issues/66

This issue is complete.
