### ISSUE TITLE
Linked data box for bibliography records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#49]

**Comment by davidamichelson** [comment]
@wsalesky Please create a Linked Data box for the individual record page in the Bibl Module using the model of the Linked Data box on the Testimonia page.

Information in this box would be derived from the following fields:

1) URL
1) Extra: CTS-URN
1) Extra: OCLC
-Note, could you investigate if there is a Linked Data or otherAPI that we might send a query to using the OCLC number and return a result if the user clicks on the link?
1) Extra: DOI
-Note, could you investigate if there is a Linked Data or other API that we might send a query to using the DOI number and return a result if the user clicks on the link?
1) Extra: xmlFile

Note for Later: when we start to include the Zotero Related items in the TEI (see #48) we will want to link to the related items in the Linked Data Box

**Comment by davidamichelson** [comment]
We would like to have this function in all Bibl modules running the Srophé app.

**Comment by wlpotter** [comment]
Oops! The link from https://github.com/srophe/caesarea-data/issues/27 should have been to #47

**Comment by wsalesky** [comment]
@davidamichelson Are all the above 'extra'  tei:idno elements? Are there some example records I can look at for testing? Thanks!

**Comment by davidamichelson** [comment]
@wlpotter and @davidamichelson will add to TEI first

**Comment by wlpotter** [comment]
Example with CTS-URN in "Extra" and a URL field: https://www.zotero.org/groups/2320447/items/TC772CD7

Example with xmlFile in "Extra" and a URL field: https://www.zotero.org/groups/2320447/items/68KPMACB

Example with DOI in "Extra": https://www.zotero.org/groups/2320447/items/CFBD6CCG

OCLC already come over as (I think) a tei:idno. This gets labelled as a URI (see [this example](http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/4P84PTWA)).

I think all of the above should be tei:idno elements?

**Comment by wsalesky** [comment]
Can we give them a subtype? Or some other easy way to easily distinguish the idnos?

**Comment by wlpotter** [comment]
I think adding a subtype (or even just changing their type) is fine. We can even just use the name of the key if we wanted, e.g. `<idno type="URI" subtype="CTS-URN">...</idno>`.

@davidamichelson thoughts?

**Comment by davidamichelson** [comment]
CTS-URN as idno with subtype="CTS-URN "
DOI as idno with subtype="DOI"
OCLC as idno with subtype="OCLC"
xmlFile as `<ref type="URL" subtype="xmlFile" target="URL to the file"/>`

**Comment by davidamichelson** [comment]
Add a note about the transform should also find Zotero field "DOI" for articles and book chapters and format them the same

**Comment by davidamichelson** [comment]
Should we check in with Nathan once we have examples

**Comment by wlpotter** [comment]
Below are some examples of the resulting TEI:

1. https://www.zotero.org/groups/2320447/items/TC772CD7 
- CTS-URN in "Extra" field
- URL field
```
<idno type="URI" subtype="CTS-URN">urn:cts:greekLit:tlg2018.tlg002.opp-grc2</idno>
<ref type="URL" target="https://scaife.perseus.org/library/urn:cts:greekLit:tlg2018.tlg002.opp-grc2/"/>
```
2. https://www.zotero.org/groups/2320447/items/68KPMACB
- xmlFile in "Extra" field
- URL field
```
<ref type="URL" target="https://ccel.org/ccel/schaff/npnf203/npnf203.iv.viii.i.i.html"/>
<ref type="URL" subtype="xmlFile" target="https://ccel.org/ccel/schaff/npnf203.xml"/>
```
3. https://www.zotero.org/groups/2320447/items/CFBD6CCG
- DOI in "Extra" field
```
<idno type="URI" subtype="DOI">10.4159/DLCL.philostratus_athens-life_apollonius_tyana.2005</idno>
```

4. https://www.zotero.org/groups/2320447/items/RIWSVZJS
- OCLC in "Extra" field

```
<idno type="URI" subtype="OCLC">http://worldcat.org/oclc/958651538</idno>
```
**Note**: The OCLC URI is constructed by the app as only the numeric string is contained in the Zotero record's "Extra" field

**Comment by davidamichelson** [comment]
Let's check in with @nathangibson to see what he thinks.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Can you look through some of the bibl records and let me know if it looks correct?

**Comment by davidamichelson** [comment]
@wsalesky 

We made two changes here. The Zotero to TEI transform should render 

Extra:CTS-URN as
```
<idno type="CTS-URN">urn:cts:greekLit:tlg2018.tlg002.opp-grc2</idno>
```
Note the change in the @srophe/issues-only 

and 

DOI in "Extra" field

```
<idno type="URI" subtype="DOI">http://dx.doi.org/10.4159/DLCL.philostratus_athens-life_apollonius_tyana.2005</idno>
```

Note, this DOI URL transform should add the base URL: "http://dx.doi.org/"

Please make these two edits. Thanks!

**Comment by wsalesky** [comment]
@davidamichelson I think this has been resolved. Please reopen if not. Thanks!
