### ISSUE TITLE
Info Box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#5]
Please create an info box based on /TEI/teiHeader/profileDesc for each individual record view

The box should come immediately below the URI

The box should be formatted as follows:

Date Composed: /TEI/teiHeader/profileDesc/creation/origDate()
Place Composed: /TEI/teiHeader/profileDesc/creation/origPlace()
Original Language: /TEI/teiHeader/profileDesc/langUsage/language()
Author: /TEI/teiHeader/profileDesc/creation/persName/@role="author"()
Title: /TEI/teiHeader/profileDesc/creation/title/@type="uniform"() Citation: /TEI/teiHeader/profileDesc/creation/ref()
URN: /TEI/teiHeader/profileDesc/textClass/classCode/idno()

--end of box--

Here are some further design notes on this information:

We would like to have elsewhere in the app a browse by function for the following 5 data points: Date Composed, Place Composed, Original Language, Author, Title (see issue #6)

Please make the text nodes displayed in the info box for Date Composed, Place Composed, Original Language, Author, Title as URLS which would take one to a Browse search for those items. In the case of Date Composed it should take the user to a timeline view. In the case of Place Composed, Original Language, Author, Title the search should be based on the @ref (or @ident for the language) rather than the text node values

Lastly, the URN: /TEI/teiHeader/profileDesc/textClass/classCode/idno() should display a resolvable URL based on the combination of the @xml:base that takes the viewer outside of our app to the relevant URL

**Comment by wsalesky** [comment]
note to self: still working on timeline view. See: #6

**Comment by wsalesky** [comment]
Added
