### ISSUE TITLE
Change testimonia "Works Cited" label to "Bibliography"

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#50]
For the bibliography section of the testimonia records, please change the label "Works Cited" to "Bibliography".

Would it also be possible to add a line-break between the numbered and non-numbered bibl items? So, for example, in [this record](http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/44), there would be an additional line-break between

2 Cornelius Tacitus, The History: Machine Readable Text, trans. Alfred John Church and William Jackson Brodribb (Medford, MA: Trustees of Tufts University, 2001), 2.79

and 

Cornelius Tacitus and Charles Dennis Fisher, Historiae (Oxford: Clarendon, 1911)., 2.82-2.83

If it would be helpful, we can have two `<listBibl>` elements, one with the numbered/footnoted bibls and the other with the non-numbered ones.

**Comment by wsalesky** [comment]
@wlpotter Yes I think you would need to separate them out into different listBibl to make that work correctly. Once you update the data let me know and I will adjust the XSLT.

**Comment by wlpotter** [comment]
Okay, I will assign this to myself to make the data change.

**Comment by wlpotter** [comment]
@wsalesky I have changed the data so that tei:bibl elements with an `@xml:id` attribute are in the first of two tei:listBibls, while all other tei:bibl elements are in a second tei:listBibl.

Cited bibls: `/TEI/text/body/listBibl[1]`
Not-Cited bibls: `/TEI/text/body/listBibl[2]`.

**Comment by wsalesky** [comment]
Fixed
