### ISSUE TITLE
Remove quote-marks from Testimonia title

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#51]
For example, the title,
"Flavius Josephus. Antiquities of the Jews 16.13" should render as 
Flavius Josephus. Antiquities of the Jews 16.13. (see http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/5)

This might be happening because they are tagged with `@level="a"`, so this may be a data issue.

**Comment by wsalesky** [comment]
Sorry, that was my bad. I added quotes via the CSS to all title[@level='a'] I changed this to only apply to the bibl elements. See: https://github.com/srophe/caesarea/issues/34
