### ISSUE TITLE
formatting updates for testimonia "How to Cite This Entry"

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#52]
I have collected several cosmetic updates fro the "How to Cite This Entry" section of testimonia records

- The entry has duplicated quote marks, one pair of which should be removed. (this is true for both the note-style and bibliography-style citation of the entry). This might be related to [this issue](https://github.com/srophe/caesarea/issues/51)
- A comma should be added at the end of this title, so "Flavius Josephus. Antiquities of the Jews 16.13" becomes "Flavius Josephus. Antiquities of the Jews 16.13," (this is true for both the note-style and bibliography-style citation of the entry)
- The text node of the `/TEI/teiHeader/fileDesc/titleStmt/editor[@role="technical"]` should be added in the "Authorial and Editorial Responsibility:" section before the "entry contributors".
For example: "David A. Michelson and William L. Potter [these values would come from the above xpath], technical editors, _Textual Evidence for Caesarea-Maritima_"

**Comment by davidamichelson** [comment]
@wsalesky Please make this change or let us know if you need clarification. Thanks!

**Comment by wsalesky** [comment]
@wlpotter can you link to a specific entry for me to use for testing?

**Comment by wlpotter** [comment]
Yes, here is an example: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/5

**Comment by wsalesky** [comment]
@wlpotter I don't see the double quotes? Maybe because it is a Monday? Where should I be looking? 

<img width="937" alt="Screen Shot 2020-06-01 at 11 58 59 AM" src="https://user-images.githubusercontent.com/1168206/83427857-641f9200-a3ff-11ea-87c1-7a898124f4e2.png">

**Comment by wlpotter** [comment]
@wsalesky I wonder if it was fixed at the same time as this issue: https://github.com/srophe/caesarea/issues/51

I must have opened them at the same time? I don't see the double quotes either.

**Comment by wsalesky** [comment]
@wlpotter Well, that makes me feel better anyway. I guess I don't need more coffee after all. 
How about the second bullet point? Is that one still valid?

**Comment by wlpotter** [comment]
@wsalesky Yes, the second and third bullet points are still issues. 

For the second point, only the note-style citation needs to be changed ("Flavius Josephus. Antiquities of the Jews 16.13" becomes "Flavius Josephus. Antiquities of the Jews 16.13," with the addition of a comma). I misspoke when I said the version under the "Bibliography" heading needs to be changed, that one is fine.

I think, also, that I was unclear about which part of the records this issue pertains to. These are edits to the citation-box at the bottom of the page `<div class="citationinfo">` rather than the tei:bibl elements themselves. Here is how it currently displays, for reference -- sorry for any confusion!

![how-to-cite](https://user-images.githubusercontent.com/44096602/83428706-86fa7800-a3f8-11ea-8773-0d2ef6bd8073.png)

**Comment by wsalesky** [comment]
@wlpotter thanks for the clarification! I try to be VERY careful when editing the citations, they are a tangled mess. Will have these done today.

**Comment by wsalesky** [comment]
@wlpotter These should all be resolved.
