### ISSUE TITLE
hover-over text for Caesarea-Maritima bibl link spacing issue

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#53]
The hover-over text for links to the Caesarea-Maritima bibl module record associated with a tei:bibl in the testimonia module is missing a space. See, for example, http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/5

In the first footnoted bibl, the link to the bibl module reads "Link to Caesarea-Maritima.org Bibliographic Record forAntiquitates Judaicae: Machine Readable Text", notice the missing space between the generic text and the bibl title. (FWIW, this issue only pertains to C-M bibl module links).

**Comment by wsalesky** [comment]
Fixed
