### ISSUE TITLE
Corrections/Additions? box recipients

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#54]
The questions/additions box should send data to both Dave and Joe

**Comment by davidamichelson** [comment]
@wsalesky Please update the Corrections/Additions? box on the app to send comments to the following two addresses: Joe Rife and David Michelson. I will send the e-mail addresses to you via e-mail rather than posting here.

**Comment by wsalesky** [comment]
@davidamichelson Please send me the email addresses

**Comment by davidamichelson** [comment]
@wsalesky Just sent them

**Comment by wsalesky** [comment]
@davidamichelson Added. This reminds me, you will need to set up recaptcha when this has a production website. I will make an issue.
