### ISSUE TITLE
collapsing and expanding long testimonia excerpts

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#56]
We may want to implement a feature where if a testimonia excerpt exceeds a predefined character length it displays in an abbreviated form by default. The user would be able to click a button to expand the text if desired.

**Comment by davidamichelson** [comment]
@wsalesky could you please add this enhancement.

When the text node in TEI:body/ab[@type="edition" or @type="translation"] is longer than 250 words, please abbreviate to 250 words (or if a character count is easier then use 3000 characters). 

Please add a button that will display the full text node. The button should read: "Show more..." 

Please have this collapse/expand function work on the columns of text at the same time (i.e. clicking the button expands both columns of Greek and English). If you have a case where the two ABs are different lengths (one less than 250 and one more then just collapse the long one).

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson Test record?

**Comment by wlpotter** [comment]
Here is a test record: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/50

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Added. Ready for review.

**Comment by davidamichelson** [comment]
Looks great!
