### ISSUE TITLE
Group Search/Browse Results of Testimonia Records by URN for Author and then Work

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#57]
See https://github.com/srophe/caesarea-data/issues/20 for the editorial discussion.

We may, based on decisions made there, need to develop a way of grouping and displaying connections between nested and container testimonia records.

See https://github.com/srophe/caesarea-data/issues/19 for any data changes involved.

**Comment by davidamichelson** [comment]
@wlpotter Please draft an example of this based on current records for @wsalesky

**Comment by davidamichelson** [comment]
@wsalesky
