### ISSUE TITLE
Browse Indexes and Pages

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#6]
(see related issue #5)

We would like to have a browse by function for the following 5 data points which are found in each record in the following path /TEI/teiHeader/profileDesc: 

1.  Date Composed(/TEI/teiHeader/profileDesc/creation/origDate)
2. Place Composed (/TEI/teiHeader/profileDesc/creation/origPlace)
3. Original Language (/TEI/teiHeader/profileDesc/langUsage/language/@ident)
4. Author (/TEI/teiHeader/profileDesc/creation/persName/@role="author")
5. Title ( /TEI/teiHeader/profileDesc/creation/title/@type="uniform")

For Date Composed it should take the user to a timeline view generated by numeric value of dates.

In the case of Place Composed, Original Language, Author, Title the browse should be based on the @ref (or @ident for the language) rather than the text node values.

**Comment by wsalesky** [comment]
Update timeline functionality to be more extensible (allow app users to plug in xpath for desired dates). 
See Caesarea timeline: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html?view=timeline

**Comment by davidamichelson** [comment]
Three browse pages:

1. Timeline (/TEI/teiHeader/profileDesc/creation/origDate)

2. Map Place Composed (/TEI/teiHeader/profileDesc/creation/origPlace)

3. Facet Text Information with Sort
a. Author (/TEI/teiHeader/profileDesc/creation/persName/@ROLE="author")
b. Work ( /TEI/teiHeader/profileDesc/creation/title/@type="uniform")
c. Original Language (/TEI/teiHeader/profileDesc/langUsage/language/@Ident)
d. Historical Era Composed(/TEI/teiHeader/profileDesc/creation/origDate  @To Be Determined)
e. Place Composed (/TEI/teiHeader/profileDesc/creation/origPlace)

**Comment by davidamichelson** [comment]
Maybe a 4th everything tab later

**Comment by wsalesky** [comment]
First draft up: 
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html

**Comment by davidamichelson** [comment]
Thanks! 

For browse by "Historical Era Composed", please change this from a numeric date browse to instead a facet by TEI:origDate/@period and then draw the values from classDecl/taxonomy/@xml:id="CM-NEAEH"

**Comment by davidamichelson** [comment]
Note some texts will have more than one @ value for TEI:origDate/@period

**Comment by davidamichelson** [comment]
Why does the timeline view have paged results (1, 2, see all)? Does that make any difference? I think the default (or even only option) for the Browse by Timeline would be All if that is possible. Thanks?

**Comment by wsalesky** [comment]
No, the paging menu should be hidden. I will take care of it.

**Comment by davidamichelson** [comment]
For the browse by map, we may need to have the app harvest coordinate date from Pleiades, should we do that through the app or should we insert that into the TEI. We should discuss this.

**Comment by davidamichelson** [comment]
FYI, the sizing of the timeline appears to have a maximum. (Expanding my widow to the full 27 inch monitor does not increase the size of the timeline after certain point). Is that just a feature of the plug-in that it is only optimized to expand to a normal size or is it something we can change?
<img width="1282" alt="Screen Shot 2020-03-19 at 11 47 30 AM" src="https://user-images.githubusercontent.com/3083773/77092445-d4f60700-69d7-11ea-8f18-1e13cc46f7f2.png">
![Screen Shot 2020-03-19 at 11 47 21 AM](https://user-images.githubusercontent.com/3083773/77092473-da535180-69d7-11ea-8c62-29df646c8711.png)

 It is not an essential thing to fix.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter are there records with `tei:teiHeader/tei:profileDesc/tei:creation/tei:origDate/@period` in them? Which branch are they on, so I can do some testing with this.

**Comment by wlpotter** [comment]
@wsalesky Yes, all the records on the master branch should have `tei:teiHeader/tei:profileDesc/tei:creation/tei:origDate/@period` attributes.

**Comment by wsalesky** [comment]
Updated. Close if it looks good.

**Comment by wsalesky** [comment]
For the map option we will need to harvest the map data. I have done this sort of thing for another project: https://anthologydev.lib.virginia.edu/lod.html?view=map

The TEI records have references to places in Getty, I use the Getty API to harvest the place data and store it in a separate TEI file which lists each as a tei:place with each TEI record referenced as tei:relation element. This file gets updated by periodically running an XQuery script, but could potentially be added to the webhooks, to work when a record is added or updated. 

Example: 
```
<place>
    <idno>http://vocab.getty.edu/tgn/7004446</idno>
    <placeName>Cologne</placeName>
    <location type="gps">
        <geo><lat>50.933333</lat><long>6.95</long></geo>
    </location>
    <listRelation>
        <relation type="mention" ana="mention"
            active="/db/apps/LiC-data/data/Shelley/shelley-frankenstein-1818.xml"
            passive="http://vocab.getty.edu/tgn/7004446">
            <desc><title type="main">Frankenstein, or The
                Modern Prometheus</title></desc>
        </relation>
    </listRelation>
</place>
```

How does this sound for the maps?

**Comment by davidamichelson** [comment]
Hey cool, is this project running srophe too? We need to update our list!

**Comment by wsalesky** [comment]
It is not using the Srophe app, although it is using some parts of app like the content negotiation module and the facets.

**Comment by wsalesky** [comment]
@davidamichelson Would you like me to do something similar for here?

**Comment by wsalesky** [comment]
Added map data see: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html?view=map

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter I think this can be closed?

**Comment by davidamichelson** [comment]
I was just wondering this. I think so other than we do want the facet box
on the map here:
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/browse.html?view=map
Is that in a separate issue somewhere?

**Comment by wsalesky** [comment]
I think it is a separate issue. (or should be)

**Comment by wsalesky** [comment]
Here: https://github.com/srophe/caesarea/issues/27
