### ISSUE TITLE
Update documentation for testimonia and bibl module to a Wiki

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#62]
Testimonia: https://docs.google.com/document/d/1NCdUi4oqsHFJ01bySrbl8yfuzL32WSPmzQR9sntKhSg/edit

Bibl: https://www.zotero.org/groups/2320447/items/9XCVFEHS

**Comment by davidamichelson** [comment]
Dump raw text into the wiki and then assign this to me to clean up :)

**Comment by wlpotter** [comment]
I have added the bibl module text to the wiki and updated the language to current practices (and added a bit of markdown).

The testimonia header is done; there is information for the tei:body, but it is slightly out of date, so I will glance through it and update that language before assigning this issue over.
