### ISSUE TITLE
Display of TEI:listRelation data in Bibl Records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#66]
@wsalesky this is related to issues #48 and #49 

See this example: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/68KPMACB

Currently the contents of TEI:listRelation display in the "Full Citation Information" part of the HTML as "Relation: https://caesarea-maritima.org/bibl/68KPMACB https://caesarea-maritima.org/bibl/P9X8IHTU"

Please remove this display. We will visualize this information in the Linked Data Box instead. See issue #49

**Comment by wsalesky** [comment]
Fixed
