### ISSUE TITLE
Bibliography Module Development

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#67]
This needs an in-person discussion.

**Comment by wsalesky** [comment]
@davidamichelson Do we need to meet sometime this week on this?

**Comment by davidamichelson** [comment]
Just to summarize our conversation:

To facilitate display, we have added two tags into the Zotero Library:

Comprehensive-Bibliography
Testimonia-Works-Cited

Only these two tags should be serialized into the TEI as TEI:seriesStmts

I suppose like this:
```
<seriesStmt>
 <title>Comprehensive Bibliography</title>
</seriesStmt>
```
```
<seriesStmt>
 <title>Testimonia Works Cited</title>
</seriesStmt>
```

Please note we have other tags in Zotero but those are for administrative purposes, so please ignore them and do not export them to the TEI.

Then based on these tags the following should be changes in the ExistDB

1. The Comprehensive Bibliography module @ exist/apps/caesarea/bibl/browse.html should only display those bibl files that have the Comprehensive Bibliography series Stmt. All others should be excluded from browse, search, etc.

2. The individual entity pages in the Testimonia module example: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/50 should stop providing the "Link to Caesarea-Maritima.org Bibliographic Record" in their Bibliography section at the bottom of the page:

example: Ammianus Marcellinus, Res Gestae: Machine Readable Text, ed. John C. Rolfe (Medford, MA: Trustees of Tufts University, 2009), 14.11 should not link to https://caesarea-maritima.org/bibl/YGM4ERYJ but should still link to https://www.zotero.org/groups/2320447/caesarea-maritima/items/YGM4ERYJ?

We can figure out how to adjust the linked data box once this change is made.

**Comment by wsalesky** [comment]
@davidamichelson Please check the updates.

**Comment by davidamichelson** [comment]
@wsalesky Thanks!

On the Testimonia entry pages, the bibl icon is successfully gone but there are two formatting issues:

1. I think there is an extra white space where the logo used to be. See image below.
2. The citations end with commas (this may have been the case before) but they should end with a period.

Example:

Current:
Ammianus Marcellinus, _Ammianus Marcellinus, with an English Translation by John C. Rolfe._, ed. John Carew Rolfe (London: W. Heinemann, 1935), 14.11, 

Corrected:
Ammianus Marcellinus, _Ammianus Marcellinus, with an English Translation by John C. Rolfe._, ed. John Carew Rolfe (London: W. Heinemann, 1935), 14.11.

Note the final period at the end of 14.11**.**

Image of extra space:
<img width="650" alt="Screen Shot 2020-08-10 at 5 00 29 PM" src="https://user-images.githubusercontent.com/3083773/89836064-9a7a3b80-db2b-11ea-872b-80ebd5ed0aa2.png">

**Comment by davidamichelson** [comment]
In other notes, the Bibliography module seems to be working exactly as desired with this change! Great work!

**Comment by davidamichelson** [comment]
@wsalesky Not sure what happened, but the bibliography module is no longer filtering based on the tags. See http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/browse.html

**Comment by wsalesky** [comment]
@davidamichelson These should all be fixed. Please check and close if it looks good to you as well.

**Comment by davidamichelson** [comment]
Looks good!
