### ISSUE TITLE
About this Text Info Box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#70]
@wsalesky Where is the file we can edit to make changes to the info box? Can  you let us know the path to that template please?

**Comment by wsalesky** [comment]
The TEI elements are called here: https://github.com/srophe/caesarea/blob/master/testimonia/record.html#L14

And they are styled by XSLT. So to add additional TEI you would add it to the above line and then edit the appropriate templates in https://github.com/srophe/caesarea/blob/master/resources/xsl/tei2html.xsl

**Comment by wsalesky** [comment]
@davidamichelson Is there any other action I need to take on this issue? If not I will un-assign myself.
