### ISSUE TITLE
In sort by title, also order by Citation Passage

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#71]
@wsalesky 

When records are displayed due to Search/Browse/Facet please order the records in this way as a default:

Group by Author (sorted Alphabetically) (the app already does this)

Then Group by Title (sorted Alphabetically) (the app already does this)

Group by citation number (which is numeric), this information is found here: /TEI/teiHeader/profileDesc/creation/ref()  -this is a new feature request

**Comment by davidamichelson** [comment]
For our information, what path does the default browse for grouping by Author and Title?

We would prefer that even in the basic browse the app be grouping results Author based on viaf URI in  /TEI/teiHeader/profileDesc/creation/persName/@ref (similar to http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/search.html?fq=;fq-Author:http://viaf.org/viaf/22143666)

And group by title based on URN found here /TEI/teiHeader/profileDesc/creation/title/@ref  similar to http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/search.html?fq=;fq-Work:urn:cts:greekLit:tlg0526.tlg001

**Comment by wsalesky** [comment]
@davidamichelson for the browse sort by title/author the sort options are here: https://github.com/srophe/caesarea/blob/master/modules/lib/data.xqm#L239

**Comment by davidamichelson** [comment]
Thanks, should we perhaps insert the VIAF and CTS URIs into the title? That
would involve changing the app less, correct?

**Comment by wsalesky** [comment]
@davidamichelson Yes that makes sense.

**Comment by wsalesky** [comment]
@davidamichelson Can you give me an example of what you are expecting to see here so I can do some testing?

**Comment by davidamichelson** [comment]
I will work on this tomorrow

**Comment by davidamichelson** [comment]
When sorting browse or search results by title, please organize by title and then by ref number:

example: https://caesarea-maritima.org/testimonia/44.tei
```
<title xml:lang="en" ref="urn:cts:latinLit:phi1351.phi004" type="uniform" level="m">The Histories</title>
<ref target="#bib44-1">2.82-2.83</ref>
```

**Comment by davidamichelson** [comment]
Looks great!
