### ISSUE TITLE
Surface /TEI/text/body/ab[@type="edition"]/idno / and TEI/text/body/ab[@type="translation"]/idno

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#72]
Based on https://github.com/srophe/caesarea-data/issues/27

Each tei:ab @type= "edition" or "translation" also has a child tei:idno. 

In every case in which this  /TEI/text/body/ab[@type="edition|translation"]/idno / has an @xml:base

Then, please append a link to the text passage in the HTML:
```
<a href="https://scaife.perseus.org/reader/urn:cts:greekLit:tlg2018.tlg002.opp-eng1:6.23">Browse source text.</a>
```

## Notes
- Please note that there are also idno elements in the path /TEI/text/body/ab[@type="identifier"]/idno /  This issue does not apply to them.

- This link will occur in line with but after the "Show more" link from issue #56 if that link is present.

- Please use the contents of the TEI:idno to construct a url which is @xml:base + idno():

example:
```
<idno xml:base="https://scaife.perseus.org/reader/">urn:cts:greekLit:tlg2018.tlg002.opp-eng1:6.23</idno>
```
Would produce the URL:

https://scaife.perseus.org/reader/urn:cts:greekLit:tlg2018.tlg002.opp-eng1:6.23

## if no @xml:base

If and only if there is no @xml:base (/TEI/text/body/ab[@type="edition|translation"]/idno /@xml:base)

Then construct the URL for the href from: the path TEI/text/body/ab[@type="edition|translation"]/idno /ref/@target

The full URL to use will be in the @target of ref. No constructing of the URL will be needed.

**Comment by davidamichelson** [comment]
@wlpotter is adding the TEI/text/body/ab[@type="edition|translation"]/idno /ref/@target data, it is not yet present.

**Comment by wsalesky** [comment]
Added
