### ISSUE TITLE
Remove the Syriac font selector in the upper right hand menu

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#77]
Please remove the Syriac font selector menu which is currently marked by an "A" in the upper right hand corner of the banner. This is not needed anywhere in the app.

<img width="219" alt="Screen Shot 2020-08-10 at 4 51 07 PM" src="https://user-images.githubusercontent.com/3083773/89835313-25f2cd00-db2a-11ea-8f8c-0d3ecede0d4b.png">

**Comment by wsalesky** [comment]
Done.
