### ISSUE TITLE
banner-text

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#78]
@wsalesky 

I would like to change the banner text for the two modules. Currently they both say "Caesarea-Maritima.org". We will keep the same logo but put "Testimonia" and "Bibliography" on each.

I went to edit it but am confused because the text just says "App Title":
https://github.com/srophe/caesarea/search?q=banner-text&unscoped_q=banner-text

Am I looking in the wrong place or is there some kind of default template that I can over-ride? Is it in the config file? And how would I split it into two module titles please?

The text I am talking about is here:

<img width="1194" alt="Screen Shot 2020-08-10 at 5 12 40 PM" src="https://user-images.githubusercontent.com/3083773/89837368-710edf00-db2e-11ea-89d1-00b12d100356.png">
<img width="1253" alt="Screen Shot 2020-08-10 at 5 12 53 PM" src="https://user-images.githubusercontent.com/3083773/89837369-71a77580-db2e-11ea-807d-f9cd706a70ab.png">

**Comment by wsalesky** [comment]
@davidamichelson You can change it from  `config:app-title` to `config:collection-title`

**Comment by davidamichelson** [comment]
@wsalesky This is fixed on the record pages but not on the browse pages. How do I get the Module Browse pages to use collection title not app title?

**Comment by davidamichelson** [comment]
Forgot to refresh the cache, it is fine!
