### ISSUE TITLE
References to Syriaca.org in Srophé App

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#79]
@wsalesky I will probably just edit most of these by hand:

https://github.com/srophe/caesarea/search?q=syriaca.org&unscoped_q=syriaca.org

Do you see any breakages that might arise?

Thanks,
Dave

**Comment by wsalesky** [comment]
Do not change any of the namespaces (these will be changed to srophe.org in the updated version of the app, see mergeMaster branch), classes or ids. The others you can change, although for most of them I don't know why you would want to change them as most of the rest are in the documentation. Is there a reason you want to change them?

**Comment by wsalesky** [comment]
Leaving open as there are few leftovers in the xquery. Do not want to change and break something.
