### ISSUE TITLE
Documentation Wiki

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#84]
@wsalesky How do we link to the correct wiki on the documentation page:

I would like this page: https://github.com/srophe/caesarea-data/wiki to be rendered on this page:
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/documentation/index.html

Can you make that change please?

**Comment by wsalesky** [comment]
Done. For future reference the links are here: https://github.com/srophe/caesarea/blob/master/documentation/index.html#L3
and:
https://github.com/srophe/caesarea/blob/master/documentation/index.html#L17

**Comment by davidamichelson** [comment]
Thanks!

**Comment by davidamichelson** [comment]
Hi @wsalesky, re-opening this, it is not behaving as expected, the links are dead. Any ideas?

**Comment by wsalesky** [comment]
@davidamichelson better?

**Comment by davidamichelson** [comment]
It worked and then I edited the wiki and it crashed it. Sorry! What did I do wrong? I changed the wiki titles did that change the URLS?

**Comment by wsalesky** [comment]
@davidamichelson looks like you may have deleted the wiki homepage?

**Comment by davidamichelson** [comment]
Wow, yes, I edited the name of the "home" page and that then meant there was no longer a home page for the wiki. I guess we are stuck with home as the name. I fixed it and everything is back
