### ISSUE TITLE
No Entries Message when Browse Testimonia by Author Letter is empty

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#88]
Example: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/browse.html?lang=&alpha-filter=D

Since there are no authors whose name begins with D, the page is empty and looks like an error.

Can we add some code that if there are no results, the message will say:

"There are no results for authors beginning with this letter."

**Comment by wsalesky** [comment]
Added.
