### ISSUE TITLE
Smart Quote Problems in the Zotero Transform?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#91]
Lookinto the single quote in this record http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/SI84MXR2

**Comment by wlpotter** [comment]
FYI, here is the updated link to the record: https://caesarea-maritima.org/bibl/SI84MXR2

**Comment by wlpotter** [comment]
This is a data issue in Zotero I think: https://www.zotero.org/groups/2320447/caesarea-maritima/items/SI84MXR2 the quotes are incorrect in the Zotero record. I can update this

**Comment by wlpotter** [comment]
Fixed in data
