### ISSUE TITLE
Remove App Level Search Bar

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#92]
For now let's hide the App Level combined search function.

So please remove the "advanced search button" and the search bar from these banners:

exist/apps/caesarea/index.html
exist/apps/caesarea/about.html
exist/apps/caesarea/documentation/index.html

**Comment by wsalesky** [comment]
Done. (These all use the page.html template, so I have simply commented it out for now.)

**Comment by davidamichelson** [comment]
Thanks! Looks like it did work!
