### ISSUE TITLE
Testimonia Advanced Search has no results

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#95]
I think there must be a bug. Thanks!

p.s. If you are able, please push a new version of the code as I have also edited the advanced search page and the search tips.

**Comment by wsalesky** [comment]
Fixed

**Comment by davidamichelson** [comment]
Hmm, keywords has results but the other three boxes on http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/search.html do not provide results, see http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/search.html?keyword=&title=&author=Eusebius%7E&placeName=

**Comment by wsalesky** [comment]
@davidamichelson I think the xpath is incorrect for these.

**Comment by wsalesky** [comment]
Fixed
