### ISSUE TITLE
search-config.xml files

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#96]
@wsalesky I want to edit the search config files for 

http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/search.html
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/search.html

I am confused on their locations, however

caesarea/search-config.xml seems to be for the testimonia
testimonia/search-config.xml seems not to be in use (it is from the gazetteer)\

and I cannot find a search-config.xml file for the bibl module.

Can you point me in the right direction please?

Thanks!

**Comment by davidamichelson** [comment]
I have edited caesarea/search-config.xml which seems to be for the testimonia but the edits are not showing up on the dev server. I must have done something wrong.

**Comment by wsalesky** [comment]
No, the webhooks are down I will have to add it manually.

**Comment by wsalesky** [comment]
@davidamichelson  The search-config.xml files are still a little experimental, they are mostly for for very simple search forms. For more complicated searches, such as the bibliography search the fields are hardcoded into the xquery. Although, this should probably be moved out into the HTML to make them easier to edit. I will add that as an issue to the Srophe application. 

For now this is where the bibl is configured: https://github.com/srophe/caesarea/blob/master/modules/search/bibl-search.xqm#L163

The testimonia search config would be caesarea/testimonia/search-config.xml

I have moved your changes and uploaded them. 
-Winona

**Comment by davidamichelson** [comment]
Thanks, testimonia search looks great. There is some edits that did not come over. Can you please move the "search tips" to the dev server? See my changes here: https://github.com/srophe/caesarea/search?q=fuzzy&unscoped_q=fuzzy

But these changes don't appear on the dev server.

**Comment by wsalesky** [comment]
done.
