### ISSUE TITLE
Top of Bibl and Testimonia Banners on Module Index Pages is getting cut off

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#97]
see http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/index.html
and http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/index.html

Both should have an h1 title such as```<h1>A Comprehensive Bibliography on Caesarea Maritima</h1>``` but it is cut off 

sorry if I did this!

**Comment by davidamichelson** [comment]
Note that this is not a problem on http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/index.html

**Comment by wsalesky** [comment]
@wsalesky No worries, I think I did that. Will fix shortly.
